# Build publication repository (GitHub) + data archive (Zenodo)

Splits outputs into two deliverables, because the trained models (~4.1GB combined) and full imputed datasets (~390MB+) are far over GitHub's 100MB per-file hard limit:

- **`<repo>_github/`** -- code, documentation, and all small result/validation/QC files. Safe to `git push`.
- **`<repo>_archive/`** -- the two best-fold models, full imputed datasets, and per-year bulk files. Upload this to **Zenodo** (free, DOI-backed, no practical size limit, integrates with a GitHub release) and link the DOI from the GitHub README and from the paper's Code/Data Availability section.

Run this **after** both pipeline notebooks and their 2025 extensions have produced their output files.

## 1. Settings

In [3]:
import os, json, shutil, hashlib, glob
import pandas as pd
from datetime import date

# --- source locations ---
QC_DIR          = 'Results/QC'
RESULTS_DIR     = {'exports': 'Results/Exports', 'imports': 'Results/Imports'}
MODEL_DIR       = 'Models'
VAL_DIR         = 'Evaluation2025'

# --- pipeline notebooks to include as the code record in the GitHub repo ---
NOTEBOOKS = [
    'Pipeline_Exports_Full.ipynb',
    'Pipeline_Imports_Full.ipynb',
    'Data_QC_non_country_codes.ipynb',
    'Build_Repository.ipynb',
]

# --- outputs ---
REPO_NAME    = 'comtrade-mirror-imputation'
GITHUB_DIR   = f'{REPO_NAME}_github'
ARCHIVE_DIR  = f'{REPO_NAME}_archive'
DATE         = date.today().isoformat()

# Fill this in once you've created the Zenodo deposit and have a DOI (can rerun just the README cell after).
ZENODO_DOI = 'PENDING -- fill in after uploading the archive zip to Zenodo'

GITHUB_FILE_LIMIT_MB = 95   # GitHub hard-blocks at 100MB; warn below that

for d in [GITHUB_DIR, ARCHIVE_DIR]:
    if os.path.exists(d):
        shutil.rmtree(d)
for sub in ['code', 'data/qc', 'data/exports', 'data/imports', 'validation', 'docs']:
    os.makedirs(os.path.join(GITHUB_DIR, sub), exist_ok=True)
for sub in ['models', 'data/exports', 'data/imports']:
    os.makedirs(os.path.join(ARCHIVE_DIR, sub), exist_ok=True)

def copy_if_exists(src, dst):
    if os.path.exists(src):
        shutil.copy2(src, dst)
        return True
    print('MISSING (skipped):', src)
    return False

print('GitHub repo  ->', os.path.abspath(GITHUB_DIR))
print('Zenodo archive ->', os.path.abspath(ARCHIVE_DIR))

GitHub repo  -> /Users/Shared/Chahinez/Imputation/Imputation [220926]/comtrade-mirror-imputation_github
Zenodo archive -> /Users/Shared/Chahinez/Imputation/Imputation [220926]/comtrade-mirror-imputation_archive

## 2. GitHub repo: code (pipeline notebooks)

In [4]:
for nb in NOTEBOOKS:
    copy_if_exists(nb, os.path.join(GITHUB_DIR, 'code', os.path.basename(nb)))

os.listdir(os.path.join(GITHUB_DIR, 'code'))

MISSING (skipped): Pipeline_Exports_Full.ipynb
MISSING (skipped): Pipeline_Imports_Full.ipynb
MISSING (skipped): Data_QC_non_country_codes.ipynb

['Build_Repository.ipynb']

## 3. GitHub repo: QC outputs

In [5]:
qc_files = ['non_country_codes.csv', 'qc_summary_exports.json', 'qc_summary_imports.json']
for f in qc_files:
    copy_if_exists(os.path.join(QC_DIR, f), os.path.join(GITHUB_DIR, 'data/qc', f))

os.listdir(os.path.join(GITHUB_DIR, 'data/qc'))

['non_country_codes.csv', 'qc_summary_exports.json', 'qc_summary_imports.json']

## 4. GitHub repo: small per-flow results + validation

In [6]:
SMALL_RESULT_FILES = [
    'missing_countries_{kind}.csv',
    'cv_folds_{kind}.csv',
    'cv_hs_{kind}.csv',
    'coverage_{kind}.csv',
    'coverage_{kind}.png',
    'summary_{kind}.csv',
    'russia_predictions_{kind}.csv',
    'model_selection_{kind}.csv',
]
VAL_FILES = [
    'val2025_folds_{kind}.csv',
    'val2025_country_{kind}.csv',
]

for kind in ['exports', 'imports']:
    dst_dir = os.path.join(GITHUB_DIR, 'data', kind)
    for pattern in SMALL_RESULT_FILES:
        copy_if_exists(os.path.join(RESULTS_DIR[kind], pattern.format(kind=kind)), os.path.join(dst_dir, pattern.format(kind=kind)))
    for pattern in VAL_FILES:
        copy_if_exists(os.path.join(VAL_DIR, pattern.format(kind=kind)), os.path.join(dst_dir, pattern.format(kind=kind)))

{k: os.listdir(os.path.join(GITHUB_DIR, 'data', k)) for k in ['exports', 'imports']}

{'exports': ['val2025_folds_exports.csv',
  'coverage_exports.csv',
  'cv_hs_exports.csv',
  'russia_predictions_exports.csv',
  'missing_countries_exports.csv',
  'summary_exports.csv',
  'model_selection_exports.csv',
  'cv_folds_exports.csv',
  'coverage_exports.png',
  'val2025_country_exports.csv'],
 'imports': ['russia_predictions_imports.csv',
  'missing_countries_imports.csv',
  'cv_hs_imports.csv',
  'coverage_imports.csv',
  'val2025_folds_imports.csv',
  'val2025_country_imports.csv',
  'coverage_imports.png',
  'cv_folds_imports.csv',
  'model_selection_imports.csv',
  'summary_imports.csv']}

## 5. Zenodo archive: best-fold models

In [7]:
for kind in ['exports', 'imports']:
    copy_if_exists(os.path.join(MODEL_DIR, f'rf_{kind}_best.joblib'), os.path.join(ARCHIVE_DIR, 'models', f'rf_{kind}_best.joblib'))

for f in os.listdir(os.path.join(ARCHIVE_DIR, 'models')):
    p = os.path.join(ARCHIVE_DIR, 'models', f)
    print(f'{os.path.getsize(p)/1e9:.2f} GB  {f}')

1.88 GB  rf_exports_best.joblib
2.26 GB  rf_imports_best.joblib

## 6. Zenodo archive: full imputed datasets + per-year bulk files

In [8]:
for kind in ['exports', 'imports']:
    dst_dir = os.path.join(ARCHIVE_DIR, 'data', kind)

    for f in glob.glob(os.path.join(RESULTS_DIR[kind], f'COMTRADE-FINAL-ALL-{kind}-imputed*.csv.gz')):
        shutil.copy2(f, os.path.join(dst_dir, os.path.basename(f)))
        print('copied', f)

    for year_dir in sorted(glob.glob(os.path.join(RESULTS_DIR[kind], '20*'))):
        if os.path.isdir(year_dir):
            dst_year_dir = os.path.join(dst_dir, 'by_year', os.path.basename(year_dir))
            shutil.copytree(year_dir, dst_year_dir, dirs_exist_ok=True)
    print(kind, 'per-year files copied')

print('Done.')

copied Results/Exports/COMTRADE-FINAL-ALL-exports-imputed-2025[2025-12-10].csv.gz
copied Results/Exports/COMTRADE-FINAL-ALL-exports-imputed[2025-12-10].csv.gz
exports per-year files copied
copied Results/Imports/COMTRADE-FINAL-ALL-imports-imputed-2025[2025-12-10].csv.gz
copied Results/Imports/COMTRADE-FINAL-ALL-imports-imputed[2025-12-10].csv.gz
imports per-year files copied
Done.

## 7. Data dictionary (GitHub repo)

In [9]:
COLUMN_DESCRIPTIONS = {
    'datasetCode': 'UN Comtrade dataset identifier.',
    'typeCode': 'Trade type (commodity/service).',
    'freqCode': 'Reporting frequency (annual).',
    'refPeriodId': 'Reference period identifier.',
    'refYear': 'Reference year of the trade flow.',
    'refMonth': 'Reference month (annual data: placeholder).',
    'period': 'Reporting period.',
    'reporterCode': 'Numeric UN Comtrade code of the reporting country.',
    'flowCode': "Trade flow direction: 'X' = export, 'M' = import.",
    'partnerCode': 'Numeric UN Comtrade code of the partner country.',
    'partner2Code': 'Secondary partner / last known destination code.',
    'classificationSearchCode': 'Commodity classification search code.',
    'classificationCode': 'Commodity classification system code (e.g. H5).',
    'isOriginalClassification': 'Whether cmdCode uses the original (not converted) classification.',
    'cmdCode': 'Harmonized System (HS) commodity code (2/4/6-digit).',
    'customsCode': 'Customs procedure code.',
    'mosCode': 'Mode of supply code.',
    'motCode': 'Mode of transport code.',
    'qtyUnitCode': 'Quantity unit code.',
    'qty': 'Reported quantity.',
    'isQtyEstimated': 'Whether quantity is estimated.',
    'altQtyUnitCode': 'Alternative quantity unit code.',
    'altQty': 'Alternative quantity value.',
    'isAltQtyEstimated': 'Whether alternative quantity is estimated.',
    'netWgt': 'Net weight (kg).',
    'isNetWgtEstimated': 'Whether net weight is estimated.',
    'grossWgt': 'Gross weight (kg).',
    'isGrossWgtEstimated': 'Whether gross weight is estimated.',
    'CIFValue': 'Cost, Insurance, Freight value (imports).',
    'FOBValue': 'Free on Board value (exports).',
    'primaryValue': 'Primary trade value in USD -- imputed for records produced by this pipeline.',
    'legacyEstimationFlag': 'Indicator for legacy estimation methods.',
    'isReported': 'True for an originally reported record; False for an imputed record produced by this pipeline.',
    'isAggregate': 'UN Comtrade commodity-level (HS-hierarchy) aggregation flag. NOTE: this is NOT a country-aggregation flag -- see QC notes below.',
}

dd = pd.DataFrame({'column': list(COLUMN_DESCRIPTIONS), 'description': list(COLUMN_DESCRIPTIONS.values())})
dd.to_csv(os.path.join(GITHUB_DIR, 'docs/DATA_DICTIONARY.csv'), index=False)
dd

,column,description
0,datasetCode,UN Comtrade dataset identifier.
1,typeCode,Trade type (commodity/service).
2,freqCode,Reporting frequency (annual).
3,refPeriodId,Reference period identifier.
4,refYear,Reference year of the trade flow.
5,refMonth,Reference month (annual data: placeholder).
6,period,Reporting period.
7,reporterCode,Numeric UN Comtrade code of the reporting coun...
8,flowCode,"Trade flow direction: 'X' = export, 'M' = import."
9,partnerCode,Numeric UN Comtrade code of the partner country.
10,partner2Code,Secondary partner / last known destination code.
11,classificationSearchCode,Commodity classification search code.
12,classificationCode,Commodity classification system code (e.g. H5).
13,isOriginalClassification,Whether cmdCode uses the original (not convert...
14,cmdCode,Harmonized System (HS) commodity code (2/4/6-d...
15,customsCode,Customs procedure code.
16,mosCode,Mode of supply code.
17,motCode,Mode of transport code.
18,qtyUnitCode,Quantity unit code.
19,qty,Reported quantity.
20,isQtyEstimated,Whether quantity is estimated.
21,altQtyUnitCode,Alternative quantity unit code.
22,altQty,Alternative quantity value.
23,isAltQtyEstimated,Whether alternative quantity is estimated.
24,netWgt,Net weight (kg).
25,isNetWgtEstimated,Whether net weight is estimated.
26,grossWgt,Gross weight (kg).
27,isGrossWgtEstimated,Whether gross weight is estimated.
28,CIFValue,"Cost, Insurance, Freight value (imports)."
29,FOBValue,Free on Board value (exports).
30,primaryValue,Primary trade value in USD -- imputed for reco...
31,legacyEstimationFlag,Indicator for legacy estimation methods.
32,isReported,True for an originally reported record; False ...
33,isAggregate,UN Comtrade commodity-level (HS-hierarchy) agg...

## 8. READMEs (auto-filled from the actual result files)

In [10]:
def read_cv(kind):
    df = pd.read_csv(os.path.join(GITHUB_DIR, 'data', kind, f'cv_folds_{kind}.csv'))
    best = df.loc[df['R2'].idxmax()]
    return df, best

def read_qc(kind):
    p = os.path.join(GITHUB_DIR, 'data/qc', f'qc_summary_{kind}.json')
    return json.load(open(p)) if os.path.exists(p) else {}

def read_missing(kind):
    p = os.path.join(GITHUB_DIR, 'data', kind, f'missing_countries_{kind}.csv')
    return pd.read_csv(p) if os.path.exists(p) else None

sections = []
for kind in ['exports', 'imports']:
    qc = read_qc(kind)
    cv, best = read_cv(kind)
    miss = read_missing(kind)
    missing_line = (f"Missing-country counts by year: " +
                     ', '.join(f"{int(r.Year)}: {int(r.N_missing)}" for r in miss.itertuples())) if miss is not None else 'n/a'
    sections.append(f"""### {kind.capitalize()}

- Rows removed by non-country/aggregate-code QC filter: {qc.get('rows_removed_pct', 'n/a')}%
- Value removed by the same filter: {qc.get('value_removed_pct', 'n/a')}%
- Best cross-validation fold: Fold {int(best['Fold'])} (R² = {best['R2']:.3f}, OOB = {best['OOB']:.3f})
- {missing_line}
""")

github_readme = f"""# {REPO_NAME}

Mirror-statistics + Random Forest imputation of missing UN Comtrade bilateral trade
records (exports and imports), 2017-2024, with a provisional 2025 extension built
from GoodTrade-sourced partner declarations.

Generated: {DATE}

**This repository holds code, documentation, and all small result files.**
The trained models (~4.1GB) and full imputed datasets (~390MB+ including
per-year files) are hosted separately on Zenodo:

> **Data + models DOI: {ZENODO_DOI}**

## Method summary

Missing country-year-commodity trade records are imputed using a Random Forest
regression model trained on partner-reported ("mirror") trade data, after excluding
non-country/aggregate reporter and partner codes (EU aggregate, World, UN Comtrade
"nes" regional buckets, Bunkers, Free Zones, Special Categories) from training --
see `data/qc/non_country_codes.csv` for the excluded code list and
`data/qc/qc_summary_{{exports,imports}}.json` for the quantified impact of that
exclusion on each pipeline run.

Evaluation uses partner-based 5-fold cross-validation (folds split by partner
country, not by row) over test years 2022-2024, reported by fold and HS level
(HS2/HS4/HS6) in `data/{{exports,imports}}/cv_folds_*.csv` and `cv_hs_*.csv`.

{''.join(sections)}
## Repository structure

```
code/          the pipeline notebooks (QC, exports, imports, this build script)
data/
  qc/          non-country/aggregate code list + QC impact summaries
  exports/     exports-side results: missing countries, CV, coverage, Russia
               case study, 2025 validation (small files only -- see Zenodo for
               the full imputed dataset)
  imports/     same, for imports
docs/          data dictionary, license
```

## Reproducing the full dataset / models

Either download them from the Zenodo DOI above, or regenerate them by running
`code/Pipeline_Exports_Full.ipynb` and `code/Pipeline_Imports_Full.ipynb`
end to end against the raw UN Comtrade source data.

## Data dictionary

See `docs/DATA_DICTIONARY.csv` for a column-by-column description of the imputed
dataset files. `isReported=False` marks rows produced by this pipeline rather
than originally declared.

## Known limitations

- `isAggregate` in the raw UN Comtrade data is a commodity-classification
  (HS-hierarchy) flag, not a country-aggregation flag -- it is not usable for
  detecting non-country reporters/partners (confirmed empirically; see QC notebook).
- 2025 figures are a provisional extension based on partner-reported GoodTrade
  declarations, not yet validated against a finalized external benchmark.
- Reported external benchmarks (BACI, IMF, World Bank) differ in scope
  (goods-only vs. goods-and-services) and valuation convention (FOB vs. CIF) from
  this HS-coded, goods-only reconstruction -- see the accompanying paper for a
  full discussion of comparability.

## Citation / license

Released under CC BY 4.0 -- see `docs/LICENSE.txt`.
"""

archive_readme = f"""# {REPO_NAME} -- data + model archive

Companion data/model archive for the GitHub repository `{REPO_NAME}`
(code, small results, documentation): <fill in GitHub URL here>

Generated: {DATE}

## Contents

```
models/        best-fold trained Random Forest models (.joblib)
               rf_exports_best.joblib, rf_imports_best.joblib
data/exports/  full imputed exports dataset (all years + 2025 extension),
               plus per-year/per-country files under by_year/
data/imports/  same, for imports
```

See the GitHub repository's `docs/DATA_DICTIONARY.csv` for column definitions
and `README.md` there for the full method description, cross-validation
results, and known limitations.

## License

Released under CC BY 4.0 -- see the GitHub repository's `docs/LICENSE.txt`.
"""

open(os.path.join(GITHUB_DIR, 'README.md'), 'w').write(github_readme)
open(os.path.join(ARCHIVE_DIR, 'README.md'), 'w').write(archive_readme)
print('Both READMEs written. Remember to fill in ZENODO_DOI and the GitHub URL once both exist, then rerun this cell + the zip cells.')

Both READMEs written. Remember to fill in ZENODO_DOI and the GitHub URL once both exist, then rerun this cell + the zip cells.

## 9. License (both)

In [11]:
license_text = """Creative Commons Attribution 4.0 International (CC BY 4.0)

This dataset and accompanying code are released under the Creative Commons
Attribution 4.0 International License.

You are free to:
  - Share -- copy and redistribute the material in any medium or format
  - Adapt -- remix, transform, and build upon the material for any purpose,
    even commercially

Under the following terms:
  - Attribution -- You must give appropriate credit, provide a link to the
    license, and indicate if changes were made.

Full license text: https://creativecommons.org/licenses/by/4.0/legalcode
"""
open(os.path.join(GITHUB_DIR, 'docs/LICENSE.txt'), 'w').write(license_text)
open(os.path.join(ARCHIVE_DIR, 'LICENSE.txt'), 'w').write(license_text)
print('LICENSE written to both.')

LICENSE written to both.

## 10. Checksums (separately, for each deliverable)

In [12]:
def sha256_of(path):
    h = hashlib.sha256()
    with open(path, 'rb') as f:
        for chunk in iter(lambda: f.read(1 << 20), b''):
            h.update(chunk)
    return h.hexdigest()

def write_checksums(root_dir):
    lines = []
    for root, _, files in os.walk(root_dir):
        for fname in sorted(files):
            fpath = os.path.join(root, fname)
            rel = os.path.relpath(fpath, root_dir)
            lines.append(f"{sha256_of(fpath)}  {rel}")
    with open(os.path.join(root_dir, 'CHECKSUMS.sha256'), 'w') as f:
        f.write('\n'.join(lines) + '\n')
    return len(lines)

n_github = write_checksums(GITHUB_DIR)
n_archive = write_checksums(ARCHIVE_DIR)
print(n_github, 'files checksummed in', GITHUB_DIR)
print(n_archive, 'files checksummed in', ARCHIVE_DIR)

27 files checksummed in comtrade-mirror-imputation_github
780 files checksummed in comtrade-mirror-imputation_archive

## 11. GitHub safety check -- fail loudly if anything is still too big

In [13]:
oversized = []
for root, _, files in os.walk(GITHUB_DIR):
    for fname in files:
        fpath = os.path.join(root, fname)
        size_mb = os.path.getsize(fpath) / 1e6
        if size_mb > GITHUB_FILE_LIMIT_MB:
            oversized.append((fpath, size_mb))

if oversized:
    print('WARNING -- these files exceed the GitHub-safe threshold and will be blocked on push:')
    for f, mb in oversized:
        print(f'  {mb:8.1f} MB  {f}')
else:
    print('OK -- no file in the GitHub repo exceeds', GITHUB_FILE_LIMIT_MB, 'MB.')

OK -- no file in the GitHub repo exceeds 95 MB.

## 12. Zip both deliverables

In [14]:
github_zip = shutil.make_archive(GITHUB_DIR, 'zip', root_dir='.', base_dir=GITHUB_DIR)
archive_zip = shutil.make_archive(ARCHIVE_DIR, 'zip', root_dir='.', base_dir=ARCHIVE_DIR)

print(f'{GITHUB_DIR}.zip  -> {os.path.getsize(github_zip)/1e6:.1f} MB  (push this to GitHub)')
print(f'{ARCHIVE_DIR}.zip -> {os.path.getsize(archive_zip)/1e9:.2f} GB  (upload this to Zenodo)')

comtrade-mirror-imputation_github.zip  -> 0.1 MB  (push this to GitHub)
comtrade-mirror-imputation_archive.zip -> 2.79 GB  (upload this to Zenodo)

## 13. Sanity check: full listing + sizes

In [15]:
for label, d in [('GITHUB', GITHUB_DIR), ('ARCHIVE', ARCHIVE_DIR)]:
    total = 0
    print(f'--- {label} ({d}) ---')
    for root, _, files in os.walk(d):
        for fname in files:
            fpath = os.path.join(root, fname)
            size = os.path.getsize(fpath)
            total += size
            print(f'{size/1e6:8.2f} MB  {os.path.relpath(fpath, d)}')
    print(f'Total: {total/1e6:.1f} MB\n')

--- GITHUB (comtrade-mirror-imputation_github) ---
    0.00 MB  README.md
    0.00 MB  CHECKSUMS.sha256
    0.33 MB  code/Build_Repository.ipynb
    0.00 MB  docs/LICENSE.txt
    0.00 MB  docs/DATA_DICTIONARY.csv
    0.00 MB  data/imports/russia_predictions_imports.csv
    0.00 MB  data/imports/missing_countries_imports.csv
    0.00 MB  data/imports/cv_hs_imports.csv
    0.00 MB  data/imports/coverage_imports.csv
    0.00 MB  data/imports/val2025_folds_imports.csv
    0.00 MB  data/imports/val2025_country_imports.csv
    0.03 MB  data/imports/coverage_imports.png
    0.00 MB  data/imports/cv_folds_imports.csv
    0.00 MB  data/imports/model_selection_imports.csv
    0.00 MB  data/imports/summary_imports.csv
    0.00 MB  data/exports/val2025_folds_exports.csv
    0.00 MB  data/exports/coverage_exports.csv
    0.00 MB  data/exports/cv_hs_exports.csv
    0.00 MB  data/exports/russia_predictions_exports.csv
    0.00 MB  data/exports/missing_countries_exports.csv
    0.00 MB  data/exports/summary_exports.csv
    0.00 MB  data/exports/model_selection_exports.csv
    0.00 MB  data/exports/cv_folds_exports.csv
    0.03 MB  data/exports/coverage_exports.png
    0.00 MB  data/exports/val2025_country_exports.csv
    0.00 MB  data/qc/non_country_codes.csv
    0.00 MB  data/qc/qc_summary_exports.json
    0.00 MB  data/qc/qc_summary_imports.json
Total: 0.4 MB

--- ARCHIVE (comtrade-mirror-imputation_archive) ---
    0.00 MB  README.md
    0.10 MB  CHECKSUMS.sha256
    0.00 MB  LICENSE.txt
 1876.95 MB  models/rf_exports_best.joblib
 2264.30 MB  models/rf_imports_best.joblib
   20.19 MB  data/imports/COMTRADE-FINAL-ALL-imports-imputed-2025[2025-12-10].csv.gz
  219.88 MB  data/imports/COMTRADE-FINAL-ALL-imports-imputed[2025-12-10].csv.gz
    0.55 MB  data/imports/by_year/2022/COMTRADE-FINAL-CA6942022H5[2025-12-10].gz
    0.30 MB  data/imports/by_year/2022/COMTRADE-FINAL-CA2752022H5[2025-12-10].gz
    0.33 MB  data/imports/by_year/2022/COMTRADE-FINAL-CA1482022H5[2025-12-10].gz
    0.42 MB  data/imports/by_year/2022/COMTRADE-FINAL-CA2262022H5[2025-12-10].gz
    0.06 MB  data/imports/by_year/2022/COMTRADE-FINAL-CA4082022H5[2025-12-10].gz
    0.58 MB  data/imports/by_year/2022/COMTRADE-FINAL-CA2622022H5[2025-12-10].gz
    0.86 MB  data/imports/by_year/2022/COMTRADE-FINAL-CA8622022H5[2025-12-10].gz
    0.54 MB  data/imports/by_year/2022/COMTRADE-FINAL-CA7952022H5[2025-12-10].gz
    0.32 MB  data/imports/by_year/2022/COMTRADE-FINAL-CA7282022H5[2025-12-10].gz
    1.52 MB  data/imports/by_year/2022/COMTRADE-FINAL-CA3682022H5[2025-12-10].gz
    0.65 MB  data/imports/by_year/2022/COMTRADE-FINAL-CA8872022H5[2025-12-10].gz
    0.50 MB  data/imports/by_year/2022/COMTRADE-FINAL-CA7062022H5[2025-12-10].gz
    0.81 MB  data/imports/by_year/2022/COMTRADE-FINAL-CA7292022H5[2025-12-10].gz
    1.04 MB  data/imports/by_year/2022/COMTRADE-FINAL-CA4342022H5[2025-12-10].gz
    3.32 MB  data/imports/by_year/2022/COMTRADE-FINAL-CA6432022H5[2025-12-10].gz
    1.41 MB  data/imports/by_year/2022/COMTRADE-FINAL-CA0502022H5[2025-12-10].gz
    0.49 MB  data/imports/by_year/2022/COMTRADE-FINAL-CA7622022H5[2025-12-10].gz
    0.65 MB  data/imports/by_year/2022/COMTRADE-FINAL-CA6462022H5[2025-12-10].gz
    1.25 MB  data/imports/by_year/2022/COMTRADE-FINAL-CA0122022H5[2025-12-10].gz
    0.42 MB  data/imports/by_year/2022/COMTRADE-FINAL-CA3322022H5[2025-12-10].gz
    0.22 MB  data/imports/by_year/2022/COMTRADE-FINAL-CA6242022H5[2025-12-10].gz
    0.79 MB  data/imports/by_year/2022/COMTRADE-FINAL-CA7802022H5[2025-12-10].gz
    1.01 MB  data/imports/by_year/2022/COMTRADE-FINAL-CA3402022H5[2025-12-10].gz
    0.40 MB  data/imports/by_year/2022/COMTRADE-FINAL-CA7602022H5[2025-12-10].gz
    0.39 MB  data/imports/by_year/2022/COMTRADE-FINAL-CA0042022H5[2025-12-10].gz
    0.17 MB  data/imports/by_year/2022/COMTRADE-FINAL-CA2322022H5[2025-12-10].gz
    1.28 MB  data/imports/by_year/2022/COMTRADE-FINAL-CA1122022H5[2025-12-10].gz
    0.82 MB  data/imports/by_year/2022/COMTRADE-FINAL-CA3242022H5[2025-12-10].gz
    0.06 MB  data/imports/by_year/2025/COMTRADE-FINAL-MRT2025H5[2025-12-10].gz
    0.31 MB  data/imports/by_year/2025/COMTRADE-FINAL-BHR2025H5[2025-12-10].gz
    0.82 MB  data/imports/by_year/2025/COMTRADE-FINAL-PER2025H5[2025-12-10].gz
    0.05 MB  data/imports/by_year/2025/COMTRADE-FINAL-LBR2025H5[2025-12-10].gz
    0.12 MB  data/imports/by_year/2025/COMTRADE-FINAL-COD2025H5[2025-12-10].gz
    0.46 MB  data/imports/by_year/2025/COMTRADE-FINAL-ALB2025H5[2025-12-10].gz
    0.86 MB  data/imports/by_year/2025/COMTRADE-FINAL-TUN2025H5[2025-12-10].gz
    0.25 MB  data/imports/by_year/2025/COMTRADE-FINAL-AFG2025H5[2025-12-10].gz
    0.13 MB  data/imports/by_year/2025/COMTRADE-FINAL-IRQ2025H5[2025-12-10].gz
    0.05 MB  data/imports/by_year/2025/COMTRADE-FINAL-TKM2025H5[2025-12-10].gz
    0.18 MB  data/imports/by_year/2025/COMTRADE-FINAL-SWZ2025H5[2025-12-10].gz
    0.09 MB  data/imports/by_year/2025/COMTRADE-FINAL-MLI2025H5[2025-12-10].gz
    0.04 MB  data/imports/by_year/2025/COMTRADE-FINAL-PSE2025H5[2025-12-10].gz
    1.40 MB  data/imports/by_year/2025/COMTRADE-FINAL-UKR2025H5[2025-12-10].gz
    0.04 MB  data/imports/by_year/2025/COMTRADE-FINAL-SDN2025H5[2025-12-10].gz
    0.34 MB  data/imports/by_year/2025/COMTRADE-FINAL-UZB2025H5[2025-12-10].gz
    0.55 MB  data/imports/by_year/2025/COMTRADE-FINAL-IRN2025H5[2025-12-10].gz
    0.05 MB  data/imports/by_year/2025/COMTRADE-FINAL-TJK2025H5[2025-12-10].gz
    0.06 MB  data/imports/by_year/2025/COMTRADE-FINAL-CUB2025H5[2025-12-10].gz
    2.17 MB  data/imports/by_year/2025/COMTRADE-FINAL-ARE2025H5[2025-12-10].gz
    0.08 MB  data/imports/by_year/2025/COMTRADE-FINAL-BEN2025H5[2025-12-10].gz
    0.08 MB  data/imports/by_year/2025/COMTRADE-FINAL-GIN2025H5[2025-12-10].gz
    0.06 MB  data/imports/by_year/2025/COMTRADE-FINAL-LBY2025H5[2025-12-10].gz
    0.06 MB  data/imports/by_year/2025/COMTRADE-FINAL-YEM2025H5[2025-12-10].gz
    0.71 MB  data/imports/by_year/2025/COMTRADE-FINAL-KHM2025H5[2025-12-10].gz
    0.12 MB  data/imports/by_year/2025/COMTRADE-FINAL-MNG2025H5[2025-12-10].gz
    0.01 MB  data/imports/by_year/2025/COMTRADE-FINAL-GNB2025H5[2025-12-10].gz
    0.36 MB  data/imports/by_year/2025/COMTRADE-FINAL-BLR2025H5[2025-12-10].gz
    0.19 MB  data/imports/by_year/2025/COMTRADE-FINAL-DZA2025H5[2025-12-10].gz
    0.21 MB  data/imports/by_year/2025/COMTRADE-FINAL-LAO2025H5[2025-12-10].gz
    0.15 MB  data/imports/by_year/2025/COMTRADE-FINAL-SLE2025H5[2025-12-10].gz
    0.15 MB  data/imports/by_year/2025/COMTRADE-FINAL-ZMB2025H5[2025-12-10].gz
    0.30 MB  data/imports/by_year/2025/COMTRADE-FINAL-MDG2025H5[2025-12-10].gz
    0.04 MB  data/imports/by_year/2025/COMTRADE-FINAL-SOM2025H5[2025-12-10].gz
    0.13 MB  data/imports/by_year/2025/COMTRADE-FINAL-ZWE2025H5[2025-12-10].gz
    0.95 MB  data/imports/by_year/2025/COMTRADE-FINAL-BGD2025H5[2025-12-10].gz
    0.09 MB  data/imports/by_year/2025/COMTRADE-FINAL-RWA2025H5[2025-12-10].gz
    0.04 MB  data/imports/by_year/2025/COMTRADE-FINAL-BDI2025H5[2025-12-10].gz
    0.03 MB  data/imports/by_year/2025/COMTRADE-FINAL-DJI2025H5[2025-12-10].gz
    0.48 MB  data/imports/by_year/2025/COMTRADE-FINAL-LBN2025H5[2025-12-10].gz
    1.11 MB  data/imports/by_year/2025/COMTRADE-FINAL-RUS2025H5[2025-12-10].gz
    0.03 MB  data/imports/by_year/2025/COMTRADE-FINAL-ERI2025H5[2025-12-10].gz
    0.22 MB  data/imports/by_year/2025/COMTRADE-FINAL-NAM2025H5[2025-12-10].gz
    0.07 MB  data/imports/by_year/2025/COMTRADE-FINAL-GAB2025H5[2025-12-10].gz
    2.58 MB  data/imports/by_year/2025/COMTRADE-FINAL-VNM2025H5[2025-12-10].gz
    0.23 MB  data/imports/by_year/2025/COMTRADE-FINAL-ETH2025H5[2025-12-10].gz
    0.47 MB  data/imports/by_year/2025/COMTRADE-FINAL-JOR2025H5[2025-12-10].gz
    0.19 MB  data/imports/by_year/2025/COMTRADE-FINAL-SEN2025H5[2025-12-10].gz
    0.20 MB  data/imports/by_year/2025/COMTRADE-FINAL-CMR2025H5[2025-12-10].gz
    0.08 MB  data/imports/by_year/2025/COMTRADE-FINAL-NER2025H5[2025-12-10].gz
    0.32 MB  data/imports/by_year/2025/COMTRADE-FINAL-NPL2025H5[2025-12-10].gz
    0.20 MB  data/imports/by_year/2025/COMTRADE-FINAL-NIC2025H5[2025-12-10].gz
    0.04 MB  data/imports/by_year/2025/COMTRADE-FINAL-GNQ2025H5[2025-12-10].gz
    0.05 MB  data/imports/by_year/2025/COMTRADE-FINAL-TCD2025H5[2025-12-10].gz
    0.39 MB  data/imports/by_year/2025/COMTRADE-FINAL-QAT2025H5[2025-12-10].gz
    0.07 MB  data/imports/by_year/2025/COMTRADE-FINAL-PNG2025H5[2025-12-10].gz
    0.04 MB  data/imports/by_year/2025/COMTRADE-FINAL-CAF2025H5[2025-12-10].gz
    0.05 MB  data/imports/by_year/2025/COMTRADE-FINAL-LSO2025H5[2025-12-10].gz
    0.08 MB  data/imports/by_year/2025/COMTRADE-FINAL-COG2025H5[2025-12-10].gz
    0.09 MB  data/imports/by_year/2025/COMTRADE-FINAL-HTI2025H5[2025-12-10].gz
    0.04 MB  data/imports/by_year/2025/COMTRADE-FINAL-GMB2025H5[2025-12-10].gz
    0.51 MB  data/imports/by_year/2025/COMTRADE-FINAL-CRI2025H5[2025-12-10].gz
    0.08 MB  data/imports/by_year/2025/COMTRADE-FINAL-BWA2025H5[2025-12-10].gz
    0.15 MB  data/imports/by_year/2025/COMTRADE-FINAL-SYR2025H5[2025-12-10].gz
    0.07 MB  data/imports/by_year/2025/COMTRADE-FINAL-PRK2025H5[2025-12-10].gz
    0.10 MB  data/imports/by_year/2025/COMTRADE-FINAL-BFA2025H5[2025-12-10].gz
    0.16 MB  data/imports/by_year/2025/COMTRADE-FINAL-VEN2025H5[2025-12-10].gz
    0.28 MB  data/imports/by_year/2025/COMTRADE-FINAL-HND2025H5[2025-12-10].gz
    0.04 MB  data/imports/by_year/2025/COMTRADE-FINAL-TLS2025H5[2025-12-10].gz
    0.84 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA3642024H5[2025-12-10].gz
    0.26 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA6242024H5[2025-12-10].gz
    0.81 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA7802024H5[2025-12-10].gz
    1.93 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA5042024H5[2025-12-10].gz
    0.48 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA4182024H5[2025-12-10].gz
    1.20 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA0122024H5[2025-12-10].gz
    0.35 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA3322024H5[2025-12-10].gz
    1.57 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA4002024H5[2025-12-10].gz
    0.87 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA1782024H5[2025-12-10].gz
    0.61 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA5242024H5[2025-12-10].gz
    0.72 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA1922024H5[2025-12-10].gz
    0.89 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA1202024H5[2025-12-10].gz
    0.89 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA4962024H5[2025-12-10].gz
    0.19 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA2322024H5[2025-12-10].gz
    0.39 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA0042024H5[2025-12-10].gz
    0.46 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA0722024H5[2025-12-10].gz
    0.83 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA3242024H5[2025-12-10].gz
    1.00 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA1122024H5[2025-12-10].gz
    2.54 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA7042024H5[2025-12-10].gz
    0.67 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA5982024H5[2025-12-10].gz
    1.55 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA5122024H5[2025-12-10].gz
    0.36 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA7602024H5[2025-12-10].gz
    1.12 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA1802024H5[2025-12-10].gz
    0.45 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA2262024H5[2025-12-10].gz
    0.34 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA1482024H5[2025-12-10].gz
    0.92 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA8622024H5[2025-12-10].gz
    0.58 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA7952024H5[2025-12-10].gz
    0.68 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA3882024H5[2025-12-10].gz
    0.67 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA4302024H5[2025-12-10].gz
    0.08 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA4082024H5[2025-12-10].gz
    0.54 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA2622024H5[2025-12-10].gz
    0.33 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA7282024H5[2025-12-10].gz
    0.55 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA6942024H5[2025-12-10].gz
    0.28 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA6262024H5[2025-12-10].gz
    1.37 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA7882024H5[2025-12-10].gz
    0.82 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA2312024H5[2025-12-10].gz
    0.63 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA4662024H5[2025-12-10].gz
    0.30 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA2752024H5[2025-12-10].gz
    0.46 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA7292024H5[2025-12-10].gz
    0.75 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA2662024H5[2025-12-10].gz
    0.32 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA1082024H5[2025-12-10].gz
    0.52 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA7622024H5[2025-12-10].gz
    1.26 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA0502024H5[2025-12-10].gz
    2.14 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA6432024H5[2025-12-10].gz
    1.04 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA4342024H5[2025-12-10].gz
    0.65 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA6462024H5[2025-12-10].gz
    1.47 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA3682024H5[2025-12-10].gz
    0.28 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA7482024H5[2025-12-10].gz
    0.57 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA8872024H5[2025-12-10].gz
    0.48 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA7062024H5[2025-12-10].gz
    1.40 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA2882024H5[2025-12-10].gz
    1.36 MB  data/imports/by_year/2024/COMTRADE-FINAL-CA0482024H5[2025-12-10].gz
    0.64 MB  data/imports/by_year/2023/COMTRADE-FINAL-CA8872023H5[2025-12-10].gz
    1.49 MB  data/imports/by_year/2023/COMTRADE-FINAL-CA3682023H5[2025-12-10].gz
    0.51 MB  data/imports/by_year/2023/COMTRADE-FINAL-CA7062023H5[2025-12-10].gz
    0.63 MB  data/imports/by_year/2023/COMTRADE-FINAL-CA7292023H5[2025-12-10].gz
    0.67 MB  data/imports/by_year/2023/COMTRADE-FINAL-CA6462023H5[2025-12-10].gz
    0.52 MB  data/imports/by_year/2023/COMTRADE-FINAL-CA7622023H5[2025-12-10].gz
    1.37 MB  data/imports/by_year/2023/COMTRADE-FINAL-CA0502023H5[2025-12-10].gz
    1.11 MB  data/imports/by_year/2023/COMTRADE-FINAL-CA4342023H5[2025-12-10].gz
    2.51 MB  data/imports/by_year/2023/COMTRADE-FINAL-CA6432023H5[2025-12-10].gz
    0.56 MB  data/imports/by_year/2023/COMTRADE-FINAL-CA6942023H5[2025-12-10].gz
    0.29 MB  data/imports/by_year/2023/COMTRADE-FINAL-CA2752023H5[2025-12-10].gz
    0.90 MB  data/imports/by_year/2023/COMTRADE-FINAL-CA8622023H5[2025-12-10].gz
    0.55 MB  data/imports/by_year/2023/COMTRADE-FINAL-CA7952023H5[2025-12-10].gz
    0.58 MB  data/imports/by_year/2023/COMTRADE-FINAL-CA2622023H5[2025-12-10].gz
    0.08 MB  data/imports/by_year/2023/COMTRADE-FINAL-CA4082023H5[2025-12-10].gz
    0.48 MB  data/imports/by_year/2023/COMTRADE-FINAL-CA2262023H5[2025-12-10].gz
    0.37 MB  data/imports/by_year/2023/COMTRADE-FINAL-CA1482023H5[2025-12-10].gz
    0.33 MB  data/imports/by_year/2023/COMTRADE-FINAL-CA7282023H5[2025-12-10].gz
    0.39 MB  data/imports/by_year/2023/COMTRADE-FINAL-CA7602023H5[2025-12-10].gz
    1.24 MB  data/imports/by_year/2023/COMTRADE-FINAL-CA1802023H5[2025-12-10].gz
    0.16 MB  data/imports/by_year/2023/COMTRADE-FINAL-CA2322023H5[2025-12-10].gz
    0.38 MB  data/imports/by_year/2023/COMTRADE-FINAL-CA0042023H5[2025-12-10].gz
    0.75 MB  data/imports/by_year/2023/COMTRADE-FINAL-CA1922023H5[2025-12-10].gz
    0.85 MB  data/imports/by_year/2023/COMTRADE-FINAL-CA3242023H5[2025-12-10].gz
    1.06 MB  data/imports/by_year/2023/COMTRADE-FINAL-CA1122023H5[2025-12-10].gz
    1.29 MB  data/imports/by_year/2023/COMTRADE-FINAL-CA0122023H5[2025-12-10].gz
    0.62 MB  data/imports/by_year/2023/COMTRADE-FINAL-CA5242023H5[2025-12-10].gz
    0.38 MB  data/imports/by_year/2023/COMTRADE-FINAL-CA3322023H5[2025-12-10].gz
    0.23 MB  data/imports/by_year/2023/COMTRADE-FINAL-CA6242023H5[2025-12-10].gz
    0.91 MB  data/imports/by_year/2023/COMTRADE-FINAL-CA3642023H5[2025-12-10].gz
    0.82 MB  data/imports/by_year/2023/COMTRADE-FINAL-CA7802023H5[2025-12-10].gz
    0.77 MB  data/imports/by_year/2017/COMTRADE-FINAL-CA2312017H5[2025-12-10].gz
    0.33 MB  data/imports/by_year/2017/COMTRADE-FINAL-CA2702017H5[2025-12-10].gz
    0.59 MB  data/imports/by_year/2017/COMTRADE-FINAL-CA4662017H5[2025-12-10].gz
    0.20 MB  data/imports/by_year/2017/COMTRADE-FINAL-CA2752017H5[2025-12-10].gz
    0.40 MB  data/imports/by_year/2017/COMTRADE-FINAL-CA6942017H5[2025-12-10].gz
    0.21 MB  data/imports/by_year/2017/COMTRADE-FINAL-CA6262017H5[2025-12-10].gz
    1.32 MB  data/imports/by_year/2017/COMTRADE-FINAL-CA7882017H5[2025-12-10].gz
    2.92 MB  data/imports/by_year/2017/COMTRADE-FINAL-CA7022017H5[2025-12-10].gz
    0.42 MB  data/imports/by_year/2017/COMTRADE-FINAL-CA4542017H5[2025-12-10].gz
    0.11 MB  data/imports/by_year/2017/COMTRADE-FINAL-CA7282017H5[2025-12-10].gz
    0.96 MB  data/imports/by_year/2017/COMTRADE-FINAL-CA6862017H5[2025-12-10].gz
    0.28 MB  data/imports/by_year/2017/COMTRADE-FINAL-CA5622017H5[2025-12-10].gz
    1.82 MB  data/imports/by_year/2017/COMTRADE-FINAL-CA6342017H5[2025-12-10].gz
    0.38 MB  data/imports/by_year/2017/COMTRADE-FINAL-CA2262017H5[2025-12-10].gz
    0.23 MB  data/imports/by_year/2017/COMTRADE-FINAL-CA1482017H5[2025-12-10].gz
    0.85 MB  data/imports/by_year/2017/COMTRADE-FINAL-CA8622017H5[2025-12-10].gz
    0.62 MB  data/imports/by_year/2017/COMTRADE-FINAL-CA3882017H5[2025-12-10].gz
    0.59 MB  data/imports/by_year/2017/COMTRADE-FINAL-CA7952017H5[2025-12-10].gz
    0.41 MB  data/imports/by_year/2017/COMTRADE-FINAL-CA2622017H5[2025-12-10].gz
    0.18 MB  data/imports/by_year/2017/COMTRADE-FINAL-CA4082017H5[2025-12-10].gz
    0.30 MB  data/imports/by_year/2017/COMTRADE-FINAL-CA7062017H5[2025-12-10].gz
    1.23 MB  data/imports/by_year/2017/COMTRADE-FINAL-CA2882017H5[2025-12-10].gz
    1.10 MB  data/imports/by_year/2017/COMTRADE-FINAL-CA0312017H5[2025-12-10].gz
    1.20 MB  data/imports/by_year/2017/COMTRADE-FINAL-CA3682017H5[2025-12-10].gz
    0.43 MB  data/imports/by_year/2017/COMTRADE-FINAL-CA8872017H5[2025-12-10].gz
    0.57 MB  data/imports/by_year/2017/COMTRADE-FINAL-CA2662017H5[2025-12-10].gz
    0.62 MB  data/imports/by_year/2017/COMTRADE-FINAL-CA4342017H5[2025-12-10].gz
    0.44 MB  data/imports/by_year/2017/COMTRADE-FINAL-CA7622017H5[2025-12-10].gz
    0.17 MB  data/imports/by_year/2017/COMTRADE-FINAL-CA1082017H5[2025-12-10].gz
    0.37 MB  data/imports/by_year/2017/COMTRADE-FINAL-CA6462017H5[2025-12-10].gz
    1.37 MB  data/imports/by_year/2017/COMTRADE-FINAL-CA5662017H5[2025-12-10].gz
    0.51 MB  data/imports/by_year/2017/COMTRADE-FINAL-CA7682017H5[2025-12-10].gz
    1.86 MB  data/imports/by_year/2017/COMTRADE-FINAL-CA6082017H5[2025-12-10].gz
    2.38 MB  data/imports/by_year/2017/COMTRADE-FINAL-CA6822017H5[2025-12-10].gz
    0.51 MB  data/imports/by_year/2017/COMTRADE-FINAL-CA3322017H5[2025-12-10].gz
    0.64 MB  data/imports/by_year/2017/COMTRADE-FINAL-CA1782017H5[2025-12-10].gz
    0.51 MB  data/imports/by_year/2017/COMTRADE-FINAL-CA5242017H5[2025-12-10].gz
    0.18 MB  data/imports/by_year/2017/COMTRADE-FINAL-CA1402017H5[2025-12-10].gz
    0.94 MB  data/imports/by_year/2017/COMTRADE-FINAL-CA8602017H5[2025-12-10].gz
    0.71 MB  data/imports/by_year/2017/COMTRADE-FINAL-CA7802017H5[2025-12-10].gz
    1.71 MB  data/imports/by_year/2017/COMTRADE-FINAL-CA0322017H5[2025-12-10].gz
    2.29 MB  data/imports/by_year/2017/COMTRADE-FINAL-CA8042017H5[2025-12-10].gz
    0.43 MB  data/imports/by_year/2017/COMTRADE-FINAL-CA2042017H5[2025-12-10].gz
    0.16 MB  data/imports/by_year/2017/COMTRADE-FINAL-CA6242017H5[2025-12-10].gz
    1.07 MB  data/imports/by_year/2017/COMTRADE-FINAL-CA4982017H5[2025-12-10].gz
    0.61 MB  data/imports/by_year/2017/COMTRADE-FINAL-CA5982017H5[2025-12-10].gz
    1.81 MB  data/imports/by_year/2017/COMTRADE-FINAL-CA8182017H5[2025-12-10].gz

In [16]:
import pandas as pd

df = pd.read_csv("Results/Exports/COMTRADE-FINAL-ALL-exports-imputed-2025[2025-12-10].csv.gz", compression="gzip")

print(df.shape)
print(df.dtypes)
df.head(20)

(2283924, 34)
datasetCode                  object
typeCode                     object
freqCode                     object
refPeriodId                 float64
refYear                       int64
refMonth                    float64
period                      float64
reporterCode                float64
flowCode                     object
partnerCode                 float64
partner2Code                float64
classificationSearchCode    float64
classificationCode           object
isOriginalClassification       bool
cmdCode                       int64
customsCode                  object
mosCode                       int64
motCode                       int64
qtyUnitCode                 float64
qty                         float64
isQtyEstimated              float64
altQtyUnitCode              float64
altQty                      float64
isAltQtyEstimated           float64
netWgt                      float64
isNetWgtEstimated           float64
grossWgt                    float64
isGrossWgtEstimated         float64
CIFValue                    float64
FOBValue                    float64
primaryValue                float64
legacyEstimationFlag         object
isReported                     bool
isAggregate                    bool
dtype: object

,datasetCode,typeCode,freqCode,refPeriodId,refYear,refMonth,period,reporterCode,flowCode,partnerCode,...,netWgt,isNetWgtEstimated,grossWgt,isGrossWgtEstimated,CIFValue,FOBValue,primaryValue,legacyEstimationFlag,isReported,isAggregate
0,H6,C,A,20250101.0,2025,NaN,2025.0,4.0,X,24.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1.265218e+07,imputed_RF,False,False
1,H6,C,A,20250101.0,2025,NaN,2025.0,4.0,X,24.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1.015943e+06,imputed_RF,False,False
2,H6,C,A,20250101.0,2025,NaN,2025.0,4.0,X,24.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1.182064e+06,imputed_RF,False,False
3,H6,C,A,20250101.0,2025,NaN,2025.0,8.0,X,24.0,...,NaN,NaN,NaN,NaN,NaN,NaN,5.146415e+05,imputed_RF,False,False
4,H6,C,A,20250101.0,2025,NaN,2025.0,8.0,X,24.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1.932152e+05,imputed_RF,False,False
5,H6,C,A,20250101.0,2025,NaN,2025.0,8.0,X,24.0,...,NaN,NaN,NaN,NaN,NaN,NaN,5.308074e+04,imputed_RF,False,False
6,H6,C,A,20250101.0,2025,NaN,2025.0,8.0,X,24.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1.996357e+05,imputed_RF,False,False
7,H6,C,A,20250101.0,2025,NaN,2025.0,8.0,X,24.0,...,NaN,NaN,NaN,NaN,NaN,NaN,5.501414e+04,imputed_RF,False,False
8,H6,C,A,20250101.0,2025,NaN,2025.0,8.0,X,24.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1.763086e+05,imputed_RF,False,False
9,H6,C,A,20250101.0,2025,NaN,2025.0,8.0,X,24.0,...,NaN,NaN,NaN,NaN,NaN,NaN,4.520456e+04,imputed_RF,False,False
10,H6,C,A,20250101.0,2025,NaN,2025.0,8.0,X,24.0,...,NaN,NaN,NaN,NaN,NaN,NaN,4.520456e+04,imputed_RF,False,False
11,H6,C,A,20250101.0,2025,NaN,2025.0,8.0,X,24.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1.400367e+05,imputed_RF,False,False
12,H6,C,A,20250101.0,2025,NaN,2025.0,8.0,X,24.0,...,NaN,NaN,NaN,NaN,NaN,NaN,4.454123e+05,imputed_RF,False,False
13,H6,C,A,20250101.0,2025,NaN,2025.0,8.0,X,24.0,...,NaN,NaN,NaN,NaN,NaN,NaN,5.763426e+04,imputed_RF,False,False
14,H6,C,A,20250101.0,2025,NaN,2025.0,12.0,X,24.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1.404216e+05,imputed_RF,False,False
15,H6,C,A,20250101.0,2025,NaN,2025.0,12.0,X,24.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1.008061e+05,imputed_RF,False,False
16,H6,C,A,20250101.0,2025,NaN,2025.0,12.0,X,24.0,...,NaN,NaN,NaN,NaN,NaN,NaN,6.327379e+04,imputed_RF,False,False
17,H6,C,A,20250101.0,2025,NaN,2025.0,12.0,X,24.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1.556765e+05,imputed_RF,False,False
18,H6,C,A,20250101.0,2025,NaN,2025.0,12.0,X,24.0,...,NaN,NaN,NaN,NaN,NaN,NaN,3.572590e+05,imputed_RF,False,False
19,H6,C,A,20250101.0,2025,NaN,2025.0,12.0,X,24.0,...,NaN,NaN,NaN,NaN,NaN,NaN,6.233145e+05,imputed_RF,False,False

In [17]:
df.columns

Index(['datasetCode', 'typeCode', 'freqCode', 'refPeriodId', 'refYear',
       'refMonth', 'period', 'reporterCode', 'flowCode', 'partnerCode',
       'partner2Code', 'classificationSearchCode', 'classificationCode',
       'isOriginalClassification', 'cmdCode', 'customsCode', 'mosCode',
       'motCode', 'qtyUnitCode', 'qty', 'isQtyEstimated', 'altQtyUnitCode',
       'altQty', 'isAltQtyEstimated', 'netWgt', 'isNetWgtEstimated',
       'grossWgt', 'isGrossWgtEstimated', 'CIFValue', 'FOBValue',
       'primaryValue', 'legacyEstimationFlag', 'isReported', 'isAggregate'],
      dtype='object')

In [2]:
# import glob
# import os
# import pandas as pd

# RESULTS_DIR = "Results"

# # Walk Results/Imports and Results/Exports (including the per-year
# # subfolders like 2017.../2024) and only touch files whose name contains
# # one of KEYWORDS. We match by substring, not by glob pattern, because the
# # "[2025-12-10]" date-stamps in your filenames are literal brackets, not
# # glob character classes -- putting them in a pattern would break matching.
# SUBDIRS = ["Imports", "Exports"]
# # per-year files are named "COMTRADE-FINAL-CA...[date].gz" (no "imputed" in
# # the name, and extension is .gz not .csv.gz) -- match on the common prefix
# # instead so both the top-level imputed files and per-year files are caught
# KEYWORDS = ["COMTRADE-FINAL"]

# STRUCTURAL_DEFAULTS = {
#     "datasetCode": "H6",          # match the classification/dataset code used in the rest of your file
#     "typeCode": "C",
#     "freqCode": "A",
#     "partner2Code": 0,
#     "customsCode": "C00",
#     "motCode": "0",
#     "mosCode": "0",
#     "isOriginalClassification": True,
#     "isReported": False,          # imputed rows, not originally reported
#     "isAggregate": False,         # already filtered to real country codes
# }


# def fill_structural(df: pd.DataFrame) -> pd.DataFrame:
#     for col, val in STRUCTURAL_DEFAULTS.items():
#         if col in df.columns:
#             df[col] = df[col].fillna(val)

#     if "period" in df.columns and "refYear" in df.columns:
#         df["period"] = df["period"].fillna(df["refYear"])
#     if "refPeriodId" in df.columns and "refYear" in df.columns:
#         df["refPeriodId"] = df["refPeriodId"].fillna(df["refYear"].astype(int) * 10000 + 101)
#     if "classificationCode" in df.columns:
#         df["classificationCode"] = df["classificationCode"].fillna("H6")
#     if "classificationSearchCode" in df.columns and "cmdCode" in df.columns:
#         df["classificationSearchCode"] = df["classificationSearchCode"].fillna(df["cmdCode"])
#     if "legacyEstimationFlag" in df.columns:
#         df["legacyEstimationFlag"] = df["legacyEstimationFlag"].fillna("imputed_RF")

#     # left as NaN (true unknowns, not derivable from GoodTrade/Comtrade inputs):
#     # qty, isQtyEstimated, altQtyUnitCode, altQty, isAltQtyEstimated, netWgt,
#     # isNetWgtEstimated, grossWgt, isGrossWgtEstimated, CIFValue, FOBValue, qtyUnitCode
#     return df


# files = set()
# for sub in SUBDIRS:
#     for path in glob.glob(os.path.join(RESULTS_DIR, sub, "**", "*.gz"), recursive=True):
#         name = os.path.basename(path)
#         if any(k in name for k in KEYWORDS):
#             files.add(path)

# print(f"found {len(files)} files")
# for f in sorted(files):
#     print(" -", f)

# for path in sorted(files):
#     before = pd.read_csv(path, compression="gzip")
#     na_before = before.isna().sum().sum()

#     after = fill_structural(before)
#     na_after = after.isna().sum().sum()

#     after.to_csv(path, index=False, compression="gzip")
#     print(f"{path}: NaN {na_before} -> {na_after}  ({before.shape[0]} rows)")

found 776 files
 - Results/Exports/2017/COMTRADE-FINAL-CA0042017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA0242017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA0312017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA0322017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA0722017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA1082017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA1202017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA1402017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA1482017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA1782017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA1802017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA1922017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA2042017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA2262017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA2312017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA2322017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA2622017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA2662017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA2702017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA2752017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA2882017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA3242017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA3322017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA3682017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA3842017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA3882017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA4042017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA4082017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA4342017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA4542017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA4662017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA4782017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA4842017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA4982017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA5242017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA5622017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA5662017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA5982017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA6082017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA6242017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA6262017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA6342017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA6462017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA6822017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA6862017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA6942017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA7022017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA7042017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA7062017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA7162017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA7282017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA7602017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA7622017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA7682017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA7802017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA7842017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA7882017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA7952017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA8002017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA8042017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA8182017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA8602017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA8622017H5[2025-12-10].gz
 - Results/Exports/2017/COMTRADE-FINAL-CA8872017H5[2025-12-10].gz
 - Results/Exports/2018/COMTRADE-FINAL-CA0042018H5[2025-12-10].gz
 - Results/Exports/2018/COMTRADE-FINAL-CA0122018H5[2025-12-10].gz
 - Results/Exports/2018/COMTRADE-FINAL-CA1082018H5[2025-12-10].gz
 - Results/Exports/2018/COMTRADE-FINAL-CA1202018H5[2025-12-10].gz
 - Results/Exports/2018/COMTRADE-FINAL-CA1402018H5[2025-12-10].gz
 - Results/Exports/2018/COMTRADE-FINAL-CA1442018H5[2025-12-10].gz
 - Results/Exports/2018/COMTRADE-FINAL-CA1482018H5[2025-12-10].gz
 - Results/Exports/2018/COMTRADE-FINAL-CA1802018H5[2025-12-10].gz
 - Results/Exports/2018/COMTRADE-FINAL-CA2042018H5[2025-12-10].gz
 - Results/Exports/2018/COMTRADE-FINAL-CA2262018H5[2025-12-10].gz
 - Results/Exports/2018/COMTRADE-FINAL-CA2312018H5[2025-12-10].gz
 - Results/Exports/2018/COMTRADE-FINAL-CA2322018H5[2025-12-10].gz
 - Results/Exports/2018/COMTRADE-FINAL-CA2622018H5[2025-12-10].gz
 - Results/Exports/2018/COMTRADE-FINAL-CA2662018H5[2025-12-10].gz
 - Results/Exports/2018/COMTRADE-FINAL-CA2702018H5[2025-12-10].gz
 - Results/Exports/2018/COMTRADE-FINAL-CA2752018H5[2025-12-10].gz
 - Results/Exports/2018/COMTRADE-FINAL-CA3242018H5[2025-12-10].gz
 - Results/Exports/2018/COMTRADE-FINAL-CA3322018H5[2025-12-10].gz
 - Results/Exports/2018/COMTRADE-FINAL-CA3682018H5[2025-12-10].gz
 - Results/Exports/2018/COMTRADE-FINAL-CA4042018H5[2025-12-10].gz
 - Results/Exports/2018/COMTRADE-FINAL-CA4082018H5[2025-12-10].gz
 - Results/Exports/2018/COMTRADE-FINAL-CA4342018H5[2025-12-10].gz
 - Results/Exports/2018/COMTRADE-FINAL-CA4542018H5[2025-12-10].gz
 - Results/Exports/2018/COMTRADE-FINAL-CA4782018H5[2025-12-10].gz
 - Results/Exports/2018/COMTRADE-FINAL-CA4842018H5[2025-12-10].gz
 - Results/Exports/2018/COMTRADE-FINAL-CA4982018H5[2025-12-10].gz
 - Results/Exports/2018/COMTRADE-FINAL-CA5242018H5[2025-12-10].gz
 - Results/Exports/2018/COMTRADE-FINAL-CA5662018H5[2025-12-10].gz
 - Results/Exports/2018/COMTRADE-FINAL-CA5982018H5[2025-12-10].gz
 - Results/Exports/2018/COMTRADE-FINAL-CA6082018H5[2025-12-10].gz
 - Results/Exports/2018/COMTRADE-FINAL-CA6262018H5[2025-12-10].gz
 - Results/Exports/2018/COMTRADE-FINAL-CA6342018H5[2025-12-10].gz
 - Results/Exports/2018/COMTRADE-FINAL-CA6822018H5[2025-12-10].gz
 - Results/Exports/2018/COMTRADE-FINAL-CA6862018H5[2025-12-10].gz
 - Results/Exports/2018/COMTRADE-FINAL-CA6942018H5[2025-12-10].gz
 - Results/Exports/2018/COMTRADE-FINAL-CA7062018H5[2025-12-10].gz
 - Results/Exports/2018/COMTRADE-FINAL-CA7282018H5[2025-12-10].gz
 - Results/Exports/2018/COMTRADE-FINAL-CA7602018H5[2025-12-10].gz
 - Results/Exports/2018/COMTRADE-FINAL-CA7622018H5[2025-12-10].gz
 - Results/Exports/2018/COMTRADE-FINAL-CA7802018H5[2025-12-10].gz
 - Results/Exports/2018/COMTRADE-FINAL-CA7952018H5[2025-12-10].gz
 - Results/Exports/2018/COMTRADE-FINAL-CA8042018H5[2025-12-10].gz
 - Results/Exports/2018/COMTRADE-FINAL-CA8182018H5[2025-12-10].gz
 - Results/Exports/2018/COMTRADE-FINAL-CA8622018H5[2025-12-10].gz
 - Results/Exports/2019/COMTRADE-FINAL-CA0042019H5[2025-12-10].gz
 - Results/Exports/2019/COMTRADE-FINAL-CA0122019H5[2025-12-10].gz
 - Results/Exports/2019/COMTRADE-FINAL-CA0502019H5[2025-12-10].gz
 - Results/Exports/2019/COMTRADE-FINAL-CA1402019H5[2025-12-10].gz
 - Results/Exports/2019/COMTRADE-FINAL-CA1482019H5[2025-12-10].gz
 - Results/Exports/2019/COMTRADE-FINAL-CA1802019H5[2025-12-10].gz
 - Results/Exports/2019/COMTRADE-FINAL-CA2262019H5[2025-12-10].gz
 - Results/Exports/2019/COMTRADE-FINAL-CA2322019H5[2025-12-10].gz
 - Results/Exports/2019/COMTRADE-FINAL-CA2622019H5[2025-12-10].gz
 - Results/Exports/2019/COMTRADE-FINAL-CA2662019H5[2025-12-10].gz
 - Results/Exports/2019/COMTRADE-FINAL-CA2702019H5[2025-12-10].gz
 - Results/Exports/2019/COMTRADE-FINAL-CA2752019H5[2025-12-10].gz
 - Results/Exports/2019/COMTRADE-FINAL-CA3242019H5[2025-12-10].gz
 - Results/Exports/2019/COMTRADE-FINAL-CA3322019H5[2025-12-10].gz
 - Results/Exports/2019/COMTRADE-FINAL-CA3682019H5[2025-12-10].gz
 - Results/Exports/2019/COMTRADE-FINAL-CA4082019H5[2025-12-10].gz
 - Results/Exports/2019/COMTRADE-FINAL-CA4262019H5[2025-12-10].gz
 - Results/Exports/2019/COMTRADE-FINAL-CA4782019H5[2025-12-10].gz
 - Results/Exports/2019/COMTRADE-FINAL-CA4842019H5[2025-12-10].gz
 - Results/Exports/2019/COMTRADE-FINAL-CA4982019H5[2025-12-10].gz
 - Results/Exports/2019/COMTRADE-FINAL-CA5662019H5[2025-12-10].gz
 - Results/Exports/2019/COMTRADE-FINAL-CA6242019H5[2025-12-10].gz
 - Results/Exports/2019/COMTRADE-FINAL-CA6262019H5[2025-12-10].gz
 - Results/Exports/2019/COMTRADE-FINAL-CA6342019H5[2025-12-10].gz
 - Results/Exports/2019/COMTRADE-FINAL-CA6462019H5[2025-12-10].gz
 - Results/Exports/2019/COMTRADE-FINAL-CA6822019H5[2025-12-10].gz
 - Results/Exports/2019/COMTRADE-FINAL-CA6942019H5[2025-12-10].gz
 - Results/Exports/2019/COMTRADE-FINAL-CA7062019H5[2025-12-10].gz
 - Results/Exports/2019/COMTRADE-FINAL-CA7282019H5[2025-12-10].gz
 - Results/Exports/2019/COMTRADE-FINAL-CA7292019H5[2025-12-10].gz
 - Results/Exports/2019/COMTRADE-FINAL-CA7602019H5[2025-12-10].gz
 - Results/Exports/2019/COMTRADE-FINAL-CA7622019H5[2025-12-10].gz
 - Results/Exports/2019/COMTRADE-FINAL-CA7802019H5[2025-12-10].gz
 - Results/Exports/2019/COMTRADE-FINAL-CA7952019H5[2025-12-10].gz
 - Results/Exports/2019/COMTRADE-FINAL-CA8042019H5[2025-12-10].gz
 - Results/Exports/2019/COMTRADE-FINAL-CA8182019H5[2025-12-10].gz
 - Results/Exports/2019/COMTRADE-FINAL-CA8622019H5[2025-12-10].gz
 - Results/Exports/2020/COMTRADE-FINAL-CA0042020H5[2025-12-10].gz
 - Results/Exports/2020/COMTRADE-FINAL-CA0122020H5[2025-12-10].gz
 - Results/Exports/2020/COMTRADE-FINAL-CA0502020H5[2025-12-10].gz
 - Results/Exports/2020/COMTRADE-FINAL-CA1402020H5[2025-12-10].gz
 - Results/Exports/2020/COMTRADE-FINAL-CA1482020H5[2025-12-10].gz
 - Results/Exports/2020/COMTRADE-FINAL-CA1802020H5[2025-12-10].gz
 - Results/Exports/2020/COMTRADE-FINAL-CA2262020H5[2025-12-10].gz
 - Results/Exports/2020/COMTRADE-FINAL-CA2322020H5[2025-12-10].gz
 - Results/Exports/2020/COMTRADE-FINAL-CA2622020H5[2025-12-10].gz
 - Results/Exports/2020/COMTRADE-FINAL-CA2702020H5[2025-12-10].gz
 - Results/Exports/2020/COMTRADE-FINAL-CA2752020H5[2025-12-10].gz
 - Results/Exports/2020/COMTRADE-FINAL-CA2882020H5[2025-12-10].gz
 - Results/Exports/2020/COMTRADE-FINAL-CA3242020H5[2025-12-10].gz
 - Results/Exports/2020/COMTRADE-FINAL-CA3322020H5[2025-12-10].gz
 - Results/Exports/2020/COMTRADE-FINAL-CA3682020H5[2025-12-10].gz
 - Results/Exports/2020/COMTRADE-FINAL-CA4082020H5[2025-12-10].gz
 - Results/Exports/2020/COMTRADE-FINAL-CA4342020H5[2025-12-10].gz
 - Results/Exports/2020/COMTRADE-FINAL-CA4842020H5[2025-12-10].gz
 - Results/Exports/2020/COMTRADE-FINAL-CA5662020H5[2025-12-10].gz
 - Results/Exports/2020/COMTRADE-FINAL-CA6242020H5[2025-12-10].gz
 - Results/Exports/2020/COMTRADE-FINAL-CA6462020H5[2025-12-10].gz
 - Results/Exports/2020/COMTRADE-FINAL-CA6822020H5[2025-12-10].gz
 - Results/Exports/2020/COMTRADE-FINAL-CA6942020H5[2025-12-10].gz
 - Results/Exports/2020/COMTRADE-FINAL-CA7062020H5[2025-12-10].gz
 - Results/Exports/2020/COMTRADE-FINAL-CA7282020H5[2025-12-10].gz
 - Results/Exports/2020/COMTRADE-FINAL-CA7292020H5[2025-12-10].gz
 - Results/Exports/2020/COMTRADE-FINAL-CA7602020H5[2025-12-10].gz
 - Results/Exports/2020/COMTRADE-FINAL-CA7622020H5[2025-12-10].gz
 - Results/Exports/2020/COMTRADE-FINAL-CA7802020H5[2025-12-10].gz
 - Results/Exports/2020/COMTRADE-FINAL-CA7952020H5[2025-12-10].gz
 - Results/Exports/2020/COMTRADE-FINAL-CA8182020H5[2025-12-10].gz
 - Results/Exports/2020/COMTRADE-FINAL-CA8622020H5[2025-12-10].gz
 - Results/Exports/2020/COMTRADE-FINAL-CA8872020H5[2025-12-10].gz
 - Results/Exports/2021/COMTRADE-FINAL-CA0042021H5[2025-12-10].gz
 - Results/Exports/2021/COMTRADE-FINAL-CA0122021H5[2025-12-10].gz
 - Results/Exports/2021/COMTRADE-FINAL-CA0502021H5[2025-12-10].gz
 - Results/Exports/2021/COMTRADE-FINAL-CA1402021H5[2025-12-10].gz
 - Results/Exports/2021/COMTRADE-FINAL-CA1482021H5[2025-12-10].gz
 - Results/Exports/2021/COMTRADE-FINAL-CA2262021H5[2025-12-10].gz
 - Results/Exports/2021/COMTRADE-FINAL-CA2322021H5[2025-12-10].gz
 - Results/Exports/2021/COMTRADE-FINAL-CA2622021H5[2025-12-10].gz
 - Results/Exports/2021/COMTRADE-FINAL-CA2752021H5[2025-12-10].gz
 - Results/Exports/2021/COMTRADE-FINAL-CA3242021H5[2025-12-10].gz
 - Results/Exports/2021/COMTRADE-FINAL-CA3322021H5[2025-12-10].gz
 - Results/Exports/2021/COMTRADE-FINAL-CA3682021H5[2025-12-10].gz
 - Results/Exports/2021/COMTRADE-FINAL-CA4082021H5[2025-12-10].gz
 - Results/Exports/2021/COMTRADE-FINAL-CA4342021H5[2025-12-10].gz
 - Results/Exports/2021/COMTRADE-FINAL-CA5662021H5[2025-12-10].gz
 - Results/Exports/2021/COMTRADE-FINAL-CA6242021H5[2025-12-10].gz
 - Results/Exports/2021/COMTRADE-FINAL-CA6462021H5[2025-12-10].gz
 - Results/Exports/2021/COMTRADE-FINAL-CA6942021H5[2025-12-10].gz
 - Results/Exports/2021/COMTRADE-FINAL-CA7062021H5[2025-12-10].gz
 - Results/Exports/2021/COMTRADE-FINAL-CA7282021H5[2025-12-10].gz
 - Results/Exports/2021/COMTRADE-FINAL-CA7292021H5[2025-12-10].gz
 - Results/Exports/2021/COMTRADE-FINAL-CA7602021H5[2025-12-10].gz
 - Results/Exports/2021/COMTRADE-FINAL-CA7622021H5[2025-12-10].gz
 - Results/Exports/2021/COMTRADE-FINAL-CA7802021H5[2025-12-10].gz
 - Results/Exports/2021/COMTRADE-FINAL-CA7952021H5[2025-12-10].gz
 - Results/Exports/2021/COMTRADE-FINAL-CA8182021H5[2025-12-10].gz
 - Results/Exports/2021/COMTRADE-FINAL-CA8622021H5[2025-12-10].gz
 - Results/Exports/2021/COMTRADE-FINAL-CA8872021H5[2025-12-10].gz
 - Results/Exports/2022/COMTRADE-FINAL-CA0042022H5[2025-12-10].gz
 - Results/Exports/2022/COMTRADE-FINAL-CA0122022H5[2025-12-10].gz
 - Results/Exports/2022/COMTRADE-FINAL-CA0502022H5[2025-12-10].gz
 - Results/Exports/2022/COMTRADE-FINAL-CA1122022H5[2025-12-10].gz
 - Results/Exports/2022/COMTRADE-FINAL-CA1482022H5[2025-12-10].gz
 - Results/Exports/2022/COMTRADE-FINAL-CA2262022H5[2025-12-10].gz
 - Results/Exports/2022/COMTRADE-FINAL-CA2322022H5[2025-12-10].gz
 - Results/Exports/2022/COMTRADE-FINAL-CA2622022H5[2025-12-10].gz
 - Results/Exports/2022/COMTRADE-FINAL-CA2752022H5[2025-12-10].gz
 - Results/Exports/2022/COMTRADE-FINAL-CA3242022H5[2025-12-10].gz
 - Results/Exports/2022/COMTRADE-FINAL-CA3322022H5[2025-12-10].gz
 - Results/Exports/2022/COMTRADE-FINAL-CA3402022H5[2025-12-10].gz
 - Results/Exports/2022/COMTRADE-FINAL-CA3682022H5[2025-12-10].gz
 - Results/Exports/2022/COMTRADE-FINAL-CA4082022H5[2025-12-10].gz
 - Results/Exports/2022/COMTRADE-FINAL-CA4342022H5[2025-12-10].gz
 - Results/Exports/2022/COMTRADE-FINAL-CA6242022H5[2025-12-10].gz
 - Results/Exports/2022/COMTRADE-FINAL-CA6432022H5[2025-12-10].gz
 - Results/Exports/2022/COMTRADE-FINAL-CA6462022H5[2025-12-10].gz
 - Results/Exports/2022/COMTRADE-FINAL-CA6942022H5[2025-12-10].gz
 - Results/Exports/2022/COMTRADE-FINAL-CA7062022H5[2025-12-10].gz
 - Results/Exports/2022/COMTRADE-FINAL-CA7282022H5[2025-12-10].gz
 - Results/Exports/2022/COMTRADE-FINAL-CA7292022H5[2025-12-10].gz
 - Results/Exports/2022/COMTRADE-FINAL-CA7602022H5[2025-12-10].gz
 - Results/Exports/2022/COMTRADE-FINAL-CA7622022H5[2025-12-10].gz
 - Results/Exports/2022/COMTRADE-FINAL-CA7802022H5[2025-12-10].gz
 - Results/Exports/2022/COMTRADE-FINAL-CA7952022H5[2025-12-10].gz
 - Results/Exports/2022/COMTRADE-FINAL-CA8622022H5[2025-12-10].gz
 - Results/Exports/2022/COMTRADE-FINAL-CA8872022H5[2025-12-10].gz
 - Results/Exports/2023/COMTRADE-FINAL-CA0042023H5[2025-12-10].gz
 - Results/Exports/2023/COMTRADE-FINAL-CA0122023H5[2025-12-10].gz
 - Results/Exports/2023/COMTRADE-FINAL-CA0502023H5[2025-12-10].gz
 - Results/Exports/2023/COMTRADE-FINAL-CA1122023H5[2025-12-10].gz
 - Results/Exports/2023/COMTRADE-FINAL-CA1482023H5[2025-12-10].gz
 - Results/Exports/2023/COMTRADE-FINAL-CA1802023H5[2025-12-10].gz
 - Results/Exports/2023/COMTRADE-FINAL-CA1922023H5[2025-12-10].gz
 - Results/Exports/2023/COMTRADE-FINAL-CA2262023H5[2025-12-10].gz
 - Results/Exports/2023/COMTRADE-FINAL-CA2322023H5[2025-12-10].gz
 - Results/Exports/2023/COMTRADE-FINAL-CA2622023H5[2025-12-10].gz
 - Results/Exports/2023/COMTRADE-FINAL-CA2752023H5[2025-12-10].gz
 - Results/Exports/2023/COMTRADE-FINAL-CA3242023H5[2025-12-10].gz
 - Results/Exports/2023/COMTRADE-FINAL-CA3322023H5[2025-12-10].gz
 - Results/Exports/2023/COMTRADE-FINAL-CA3642023H5[2025-12-10].gz
 - Results/Exports/2023/COMTRADE-FINAL-CA3682023H5[2025-12-10].gz
 - Results/Exports/2023/COMTRADE-FINAL-CA4082023H5[2025-12-10].gz
 - Results/Exports/2023/COMTRADE-FINAL-CA4342023H5[2025-12-10].gz
 - Results/Exports/2023/COMTRADE-FINAL-CA5242023H5[2025-12-10].gz
 - Results/Exports/2023/COMTRADE-FINAL-CA6242023H5[2025-12-10].gz
 - Results/Exports/2023/COMTRADE-FINAL-CA6432023H5[2025-12-10].gz
 - Results/Exports/2023/COMTRADE-FINAL-CA6462023H5[2025-12-10].gz
 - Results/Exports/2023/COMTRADE-FINAL-CA6942023H5[2025-12-10].gz
 - Results/Exports/2023/COMTRADE-FINAL-CA7062023H5[2025-12-10].gz
 - Results/Exports/2023/COMTRADE-FINAL-CA7282023H5[2025-12-10].gz
 - Results/Exports/2023/COMTRADE-FINAL-CA7292023H5[2025-12-10].gz
 - Results/Exports/2023/COMTRADE-FINAL-CA7602023H5[2025-12-10].gz
 - Results/Exports/2023/COMTRADE-FINAL-CA7622023H5[2025-12-10].gz
 - Results/Exports/2023/COMTRADE-FINAL-CA7802023H5[2025-12-10].gz
 - Results/Exports/2023/COMTRADE-FINAL-CA7952023H5[2025-12-10].gz
 - Results/Exports/2023/COMTRADE-FINAL-CA8622023H5[2025-12-10].gz
 - Results/Exports/2023/COMTRADE-FINAL-CA8872023H5[2025-12-10].gz
 - Results/Exports/2024/COMTRADE-FINAL-CA0042024H5[2025-12-10].gz
 - Results/Exports/2024/COMTRADE-FINAL-CA0122024H5[2025-12-10].gz
 - Results/Exports/2024/COMTRADE-FINAL-CA0482024H5[2025-12-10].gz
 - Results/Exports/2024/COMTRADE-FINAL-CA0502024H5[2025-12-10].gz
 - Results/Exports/2024/COMTRADE-FINAL-CA0722024H5[2025-12-10].gz
 - Results/Exports/2024/COMTRADE-FINAL-CA1082024H5[2025-12-10].gz
 - Results/Exports/2024/COMTRADE-FINAL-CA1122024H5[2025-12-10].gz
 - Results/Exports/2024/COMTRADE-FINAL-CA1202024H5[2025-12-10].gz
 - Results/Exports/2024/COMTRADE-FINAL-CA1482024H5[2025-12-10].gz
 - Results/Exports/2024/COMTRADE-FINAL-CA1782024H5[2025-12-10].gz
 - Results/Exports/2024/COMTRADE-FINAL-CA1802024H5[2025-12-10].gz
 - Results/Exports/2024/COMTRADE-FINAL-CA1922024H5[2025-12-10].gz
 - Results/Exports/2024/COMTRADE-FINAL-CA2262024H5[2025-12-10].gz
 - Results/Exports/2024/COMTRADE-FINAL-CA2312024H5[2025-12-10].gz
 - Results/Exports/2024/COMTRADE-FINAL-CA2322024H5[2025-12-10].gz
 - Results/Exports/2024/COMTRADE-FINAL-CA2622024H5[2025-12-10].gz
 - Results/Exports/2024/COMTRADE-FINAL-CA2662024H5[2025-12-10].gz
 - Results/Exports/2024/COMTRADE-FINAL-CA2752024H5[2025-12-10].gz
 - Results/Exports/2024/COMTRADE-FINAL-CA2882024H5[2025-12-10].gz
 - Results/Exports/2024/COMTRADE-FINAL-CA3242024H5[2025-12-10].gz
 - Results/Exports/2024/COMTRADE-FINAL-CA3322024H5[2025-12-10].gz
 - Results/Exports/2024/COMTRADE-FINAL-CA3642024H5[2025-12-10].gz
 - Results/Exports/2024/COMTRADE-FINAL-CA3682024H5[2025-12-10].gz
 - Results/Exports/2024/COMTRADE-FINAL-CA3882024H5[2025-12-10].gz
 - Results/Exports/2024/COMTRADE-FINAL-CA4002024H5[2025-12-10].gz
 - Results/Exports/2024/COMTRADE-FINAL-CA4082024H5[2025-12-10].gz
 - Results/Exports/2024/COMTRADE-FINAL-CA4182024H5[2025-12-10].gz
 - Results/Exports/2024/COMTRADE-FINAL-CA4302024H5[2025-12-10].gz
 - Results/Exports/2024/COMTRADE-FINAL-CA4342024H5[2025-12-10].gz
 - Results/Exports/2024/COMTRADE-FINAL-CA4662024H5[2025-12-10].gz
 - Results/Exports/2024/COMTRADE-FINAL-CA4962024H5[2025-12-10].gz
 - Results/Exports/2024/COMTRADE-FINAL-CA5042024H5[2025-12-10].gz
 - Results/Exports/2024/COMTRADE-FINAL-CA5122024H5[2025-12-10].gz
 - Results/Exports/2024/COMTRADE-FINAL-CA5242024H5[2025-12-10].gz
 - Results/Exports/2024/COMTRADE-FINAL-CA5982024H5[2025-12-10].gz
 - Results/Exports/2024/COMTRADE-FINAL-CA6242024H5[2025-12-10].gz
 - Results/Exports/2024/COMTRADE-FINAL-CA6262024H5[2025-12-10].gz

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-AFG2025H5[2025-12-10].gz: NaN 367444 -> 170599  (13123 rows)
Results/Exports/2025/COMTRADE-FINAL-ALB2025H5[2025-12-10].gz: NaN 1524068 -> 707603  (54431 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-ARE2025H5[2025-12-10].gz: NaN 4229064 -> 1963494  (151038 rows)
Results/Exports/2025/COMTRADE-FINAL-BDI2025H5[2025-12-10].gz: NaN 337428 -> 156663  (12051 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-BEN2025H5[2025-12-10].gz: NaN 675668 -> 313703  (24131 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-BFA2025H5[2025-12-10].gz: NaN 730940 -> 339365  (26105 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-BGD2025H5[2025-12-10].gz: NaN 1320704 -> 613184  (47168 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-BHR2025H5[2025-12-10].gz: NaN 1566936 -> 727506  (55962 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-BLR2025H5[2025-12-10].gz: NaN 865732 -> 401947  (30919 rows)
Results/Exports/2025/COMTRADE-FINAL-BWA2025H5[2025-12-10].gz: NaN 461300 -> 214175  (16475 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-CAF2025H5[2025-12-10].gz: NaN 246120 -> 114270  (8790 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-CMR2025H5[2025-12-10].gz: NaN 939064 -> 435994  (33538 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-COD2025H5[2025-12-10].gz: NaN 1076040 -> 499590  (38430 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-COG2025H5[2025-12-10].gz: NaN 888160 -> 412360  (31720 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-CRI2025H5[2025-12-10].gz: NaN 1546440 -> 717990  (55230 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-CUB2025H5[2025-12-10].gz: NaN 757988 -> 351923  (27071 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-DJI2025H5[2025-12-10].gz: NaN 545916 -> 253461  (19497 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-DZA2025H5[2025-12-10].gz: NaN 1282344 -> 595374  (45798 rows)
Results/Exports/2025/COMTRADE-FINAL-ERI2025H5[2025-12-10].gz: NaN 190092 -> 88257  (6789 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-ETH2025H5[2025-12-10].gz: NaN 882140 -> 409565  (31505 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-GAB2025H5[2025-12-10].gz: NaN 770448 -> 357708  (27516 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-GIN2025H5[2025-12-10].gz: NaN 926380 -> 430105  (33085 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-GMB2025H5[2025-12-10].gz: NaN 478128 -> 221988  (17076 rows)
Results/Exports/2025/COMTRADE-FINAL-GNB2025H5[2025-12-10].gz: NaN 270984 -> 125814  (9678 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-GNQ2025H5[2025-12-10].gz: NaN 492716 -> 228761  (17597 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-HND2025H5[2025-12-10].gz: NaN 1060976 -> 492596  (37892 rows)
Results/Exports/2025/COMTRADE-FINAL-HTI2025H5[2025-12-10].gz: NaN 402668 -> 186953  (14381 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-IRN2025H5[2025-12-10].gz: NaN 834568 -> 387478  (29806 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-IRQ2025H5[2025-12-10].gz: NaN 1442980 -> 669955  (51535 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-JOR2025H5[2025-12-10].gz: NaN 1637132 -> 760097  (58469 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-KHM2025H5[2025-12-10].gz: NaN 1024772 -> 475787  (36599 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-LAO2025H5[2025-12-10].gz: NaN 512568 -> 237978  (18306 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-LBN2025H5[2025-12-10].gz: NaN 1627276 -> 755521  (58117 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-LBR2025H5[2025-12-10].gz: NaN 720132 -> 334347  (25719 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-LBY2025H5[2025-12-10].gz: NaN 1098020 -> 509795  (39215 rows)
Results/Exports/2025/COMTRADE-FINAL-LSO2025H5[2025-12-10].gz: NaN 231420 -> 107445  (8265 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-MDG2025H5[2025-12-10].gz: NaN 803544 -> 373074  (28698 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-MLI2025H5[2025-12-10].gz: NaN 618100 -> 286975  (22075 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-MNG2025H5[2025-12-10].gz: NaN 977200 -> 453700  (34900 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-MRT2025H5[2025-12-10].gz: NaN 724304 -> 336284  (25868 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-NAM2025H5[2025-12-10].gz: NaN 734244 -> 340899  (26223 rows)
Results/Exports/2025/COMTRADE-FINAL-NER2025H5[2025-12-10].gz: NaN 289212 -> 134277  (10329 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-NIC2025H5[2025-12-10].gz: NaN 795956 -> 369551  (28427 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-NPL2025H5[2025-12-10].gz: NaN 664188 -> 308373  (23721 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-PER2025H5[2025-12-10].gz: NaN 1933148 -> 897533  (69041 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-PNG2025H5[2025-12-10].gz: NaN 723212 -> 335777  (25829 rows)
Results/Exports/2025/COMTRADE-FINAL-PRK2025H5[2025-12-10].gz: NaN 90048 -> 41808  (3216 rows)
Results/Exports/2025/COMTRADE-FINAL-PSE2025H5[2025-12-10].gz: NaN 304780 -> 141505  (10885 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-QAT2025H5[2025-12-10].gz: NaN 2126404 -> 987259  (75943 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-RUS2025H5[2025-12-10].gz: NaN 2013844 -> 934999  (71923 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-RWA2025H5[2025-12-10].gz: NaN 707896 -> 328666  (25282 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-SDN2025H5[2025-12-10].gz: NaN 496384 -> 230464  (17728 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-SEN2025H5[2025-12-10].gz: NaN 1244768 -> 577928  (44456 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-SLE2025H5[2025-12-10].gz: NaN 615916 -> 285961  (21997 rows)
Results/Exports/2025/COMTRADE-FINAL-SOM2025H5[2025-12-10].gz: NaN 473900 -> 220025  (16925 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-SWZ2025H5[2025-12-10].gz: NaN 296940 -> 137865  (10605 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-SYR2025H5[2025-12-10].gz: NaN 580160 -> 269360  (20720 rows)
Results/Exports/2025/COMTRADE-FINAL-TCD2025H5[2025-12-10].gz: NaN 384468 -> 178503  (13731 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-TJK2025H5[2025-12-10].gz: NaN 515984 -> 239564  (18428 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-TKM2025H5[2025-12-10].gz: NaN 609084 -> 282789  (21753 rows)
Results/Exports/2025/COMTRADE-FINAL-TLS2025H5[2025-12-10].gz: NaN 343084 -> 159289  (12253 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-TUN2025H5[2025-12-10].gz: NaN 1507688 -> 699998  (53846 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-UKR2025H5[2025-12-10].gz: NaN 2332932 -> 1083147  (83319 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-UZB2025H5[2025-12-10].gz: NaN 1513512 -> 702702  (54054 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-VEN2025H5[2025-12-10].gz: NaN 947268 -> 439803  (33831 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-VNM2025H5[2025-12-10].gz: NaN 2620912 -> 1216852  (93604 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-YEM2025H5[2025-12-10].gz: NaN 537320 -> 249470  (19190 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-ZMB2025H5[2025-12-10].gz: NaN 819840 -> 380640  (29280 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/2025/COMTRADE-FINAL-ZWE2025H5[2025-12-10].gz: NaN 638876 -> 296621  (22817 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Exports/COMTRADE-FINAL-ALL-exports-imputed-2025[2025-12-10].csv.gz: NaN 63949872 -> 29691012  (2283924 rows)
Results/Exports/COMTRADE-FINAL-ALL-exports-imputed[2025-12-10].csv.gz: NaN 4515737 -> 4515737  (5157767 rows)
Results/Imports/2017/COMTRADE-FINAL-CA0042017H5[2025-12-10].gz: NaN 22483 -> 22483  (22061 rows)
Results/Imports/2017/COMTRADE-FINAL-CA0242017H5[2025-12-10].gz: NaN 45069 -> 45069  (44430 rows)
Results/Imports/2017/COMTRADE-FINAL-CA0312017H5[2025-12-10].gz: NaN 46185 -> 46185  (45970 rows)
Results/Imports/2017/COMTRADE-FINAL-CA0322017H5[2025-12-10].gz: NaN 67610 -> 67610  (66466 rows)
Results/Imports/2017/COMTRADE-FINAL-CA0722017H5[2025-12-10].gz: NaN 17636 -> 17636  (17160 rows)
Results/Imports/2017/COMTRADE-FINAL-CA1082017H5[2025-12-10].gz: NaN 7814 -> 7814  (7693 rows)
Results/Imports/2017/COMTRADE-FINAL-CA1202017H5[2025-12-10].gz: NaN 32930 -> 32930  (32585 rows)
Results/Imports/2017/COMTRADE-FINAL-CA1402017H5[2025-12-10].gz: NaN 8136 -> 8136  (8037 rows)
Results/Imports/2017/COMTRADE-FINAL-CA1482017H5[2025-12-10].gz: NaN 10395 -> 10395  (10211 rows)
Results/Imports/2017/COMTRADE-FINAL-CA1782017H5[2025-12-10].gz: NaN 27469 -> 27469  (27107 rows)
Results/Imports/2017/COMTRADE-FINAL-CA1802017H5[2025-12-10].gz: NaN 29938 -> 29938  (29372 rows)
Results/Imports/2017/COMTRADE-FINAL-CA1922017H5[2025-12-10].gz: NaN 32906 -> 32906  (32253 rows)
Results/Imports/2017/COMTRADE-FINAL-CA2042017H5[2025-12-10].gz: NaN 18652 -> 18652  (18456 rows)
Results/Imports/2017/COMTRADE-FINAL-CA2262017H5[2025-12-10].gz: NaN 16215 -> 16215  (16269 rows)
Results/Imports/2017/COMTRADE-FINAL-CA2312017H5[2025-12-10].gz: NaN 32143 -> 32143  (31633 rows)
Results/Imports/2017/COMTRADE-FINAL-CA2322017H5[2025-12-10].gz: NaN 6141 -> 6141  (6054 rows)
Results/Imports/2017/COMTRADE-FINAL-CA2622017H5[2025-12-10].gz: NaN 17433 -> 17433  (17122 rows)
Results/Imports/2017/COMTRADE-FINAL-CA2662017H5[2025-12-10].gz: NaN 24391 -> 24391  (24165 rows)
Results/Imports/2017/COMTRADE-FINAL-CA2702017H5[2025-12-10].gz: NaN 14352 -> 14352  (14202 rows)
Results/Imports/2017/COMTRADE-FINAL-CA2752017H5[2025-12-10].gz: NaN 8432 -> 8432  (8390 rows)
Results/Imports/2017/COMTRADE-FINAL-CA2882017H5[2025-12-10].gz: NaN 51150 -> 51150  (50386 rows)
Results/Imports/2017/COMTRADE-FINAL-CA3242017H5[2025-12-10].gz: NaN 27302 -> 27302  (26985 rows)
Results/Imports/2017/COMTRADE-FINAL-CA3322017H5[2025-12-10].gz: NaN 21311 -> 21311  (20889 rows)
Results/Imports/2017/COMTRADE-FINAL-CA3682017H5[2025-12-10].gz: NaN 48740 -> 48740  (48228 rows)
Results/Imports/2017/COMTRADE-FINAL-CA3842017H5[2025-12-10].gz: NaN 41051 -> 41051  (40538 rows)
Results/Imports/2017/COMTRADE-FINAL-CA3882017H5[2025-12-10].gz: NaN 26234 -> 26234  (25408 rows)
Results/Imports/2017/COMTRADE-FINAL-CA4042017H5[2025-12-10].gz: NaN 49187 -> 49187  (48341 rows)
Results/Imports/2017/COMTRADE-FINAL-CA4082017H5[2025-12-10].gz: NaN 7772 -> 7772  (7682 rows)
Results/Imports/2017/COMTRADE-FINAL-CA4342017H5[2025-12-10].gz: NaN 25460 -> 25460  (25359 rows)
Results/Imports/2017/COMTRADE-FINAL-CA4542017H5[2025-12-10].gz: NaN 18033 -> 18033  (17547 rows)
Results/Imports/2017/COMTRADE-FINAL-CA4662017H5[2025-12-10].gz: NaN 25134 -> 25134  (24899 rows)
Results/Imports/2017/COMTRADE-FINAL-CA4782017H5[2025-12-10].gz: NaN 22588 -> 22588  (22422 rows)
Results/Imports/2017/COMTRADE-FINAL-CA4842017H5[2025-12-10].gz: NaN 96656 -> 96656  (95610 rows)
Results/Imports/2017/COMTRADE-FINAL-CA4982017H5[2025-12-10].gz: NaN 44443 -> 44443  (44750 rows)
Results/Imports/2017/COMTRADE-FINAL-CA5242017H5[2025-12-10].gz: NaN 21348 -> 21348  (20865 rows)
Results/Imports/2017/COMTRADE-FINAL-CA5622017H5[2025-12-10].gz: NaN 12521 -> 12521  (12335 rows)
Results/Imports/2017/COMTRADE-FINAL-CA5662017H5[2025-12-10].gz: NaN 56138 -> 56138  (55370 rows)
Results/Imports/2017/COMTRADE-FINAL-CA5982017H5[2025-12-10].gz: NaN 25307 -> 25307  (24377 rows)
Results/Imports/2017/COMTRADE-FINAL-CA6082017H5[2025-12-10].gz: NaN 73442 -> 73442  (71917 rows)
Results/Imports/2017/COMTRADE-FINAL-CA6242017H5[2025-12-10].gz: NaN 7204 -> 7204  (7158 rows)
Results/Imports/2017/COMTRADE-FINAL-CA6262017H5[2025-12-10].gz: NaN 9209 -> 9209  (9039 rows)
Results/Imports/2017/COMTRADE-FINAL-CA6342017H5[2025-12-10].gz: NaN 73651 -> 73651  (72799 rows)
Results/Imports/2017/COMTRADE-FINAL-CA6462017H5[2025-12-10].gz: NaN 16494 -> 16494  (16305 rows)
Results/Imports/2017/COMTRADE-FINAL-CA6822017H5[2025-12-10].gz: NaN 93388 -> 93388  (92074 rows)
Results/Imports/2017/COMTRADE-FINAL-CA6862017H5[2025-12-10].gz: NaN 40085 -> 40085  (39582 rows)
Results/Imports/2017/COMTRADE-FINAL-CA6942017H5[2025-12-10].gz: NaN 17407 -> 17407  (17149 rows)
Results/Imports/2017/COMTRADE-FINAL-CA7022017H5[2025-12-10].gz: NaN 115190 -> 115190  (112585 rows)
Results/Imports/2017/COMTRADE-FINAL-CA7042017H5[2025-12-10].gz: NaN 88790 -> 88790  (87477 rows)
Results/Imports/2017/COMTRADE-FINAL-CA7062017H5[2025-12-10].gz: NaN 12936 -> 12936  (12761 rows)
Results/Imports/2017/COMTRADE-FINAL-CA7162017H5[2025-12-10].gz: NaN 21151 -> 21151  (20596 rows)
Results/Imports/2017/COMTRADE-FINAL-CA7282017H5[2025-12-10].gz: NaN 5112 -> 5112  (5028 rows)
Results/Imports/2017/COMTRADE-FINAL-CA7602017H5[2025-12-10].gz: NaN 21083 -> 21083  (20959 rows)
Results/Imports/2017/COMTRADE-FINAL-CA7622017H5[2025-12-10].gz: NaN 18366 -> 18366  (18700 rows)
Results/Imports/2017/COMTRADE-FINAL-CA7682017H5[2025-12-10].gz: NaN 21986 -> 21986  (21718 rows)
Results/Imports/2017/COMTRADE-FINAL-CA7802017H5[2025-12-10].gz: NaN 30019 -> 30019  (29089 rows)
Results/Imports/2017/COMTRADE-FINAL-CA7842017H5[2025-12-10].gz: NaN 131398 -> 131398  (129811 rows)
Results/Imports/2017/COMTRADE-FINAL-CA7882017H5[2025-12-10].gz: NaN 52193 -> 52193  (51777 rows)
Results/Imports/2017/COMTRADE-FINAL-CA7952017H5[2025-12-10].gz: NaN 24929 -> 24929  (24681 rows)
Results/Imports/2017/COMTRADE-FINAL-CA8002017H5[2025-12-10].gz: NaN 28013 -> 28013  (27567 rows)
Results/Imports/2017/COMTRADE-FINAL-CA8042017H5[2025-12-10].gz: NaN 90334 -> 90334  (90190 rows)
Results/Imports/2017/COMTRADE-FINAL-CA8182017H5[2025-12-10].gz: NaN 71184 -> 71184  (70593 rows)
Results/Imports/2017/COMTRADE-FINAL-CA8602017H5[2025-12-10].gz: NaN 37860 -> 37860  (37609 rows)
Results/Imports/2017/COMTRADE-FINAL-CA8622017H5[2025-12-10].gz: NaN 34466 -> 34466  (33650 rows)
Results/Imports/2017/COMTRADE-FINAL-CA8872017H5[2025-12-10].gz: NaN 17179 -> 17179  (17010 rows)
Results/Imports/2018/COMTRADE-FINAL-CA0042018H5[2025-12-10].gz: NaN 28118 -> 28118  (27012 rows)
Results/Imports/2018/COMTRADE-FINAL-CA0122018H5[2025-12-10].gz: NaN 53663 -> 53663  (51662 rows)
Results/Imports/2018/COMTRADE-FINAL-CA1082018H5[2025-12-10].gz: NaN 10721 -> 10721  (10832 rows)
Results/Imports/2018/COMTRADE-FINAL-CA1202018H5[2025-12-10].gz: NaN 38850 -> 38850  (37681 rows)
Results/Imports/2018/COMTRADE-FINAL-CA1402018H5[2025-12-10].gz: NaN 10671 -> 10671  (10051 rows)
Results/Imports/2018/COMTRADE-FINAL-CA1442018H5[2025-12-10].gz: NaN 57014 -> 57014  (55053 rows)
Results/Imports/2018/COMTRADE-FINAL-CA1482018H5[2025-12-10].gz: NaN 13469 -> 13469  (12945 rows)
Results/Imports/2018/COMTRADE-FINAL-CA1802018H5[2025-12-10].gz: NaN 39360 -> 39360  (40872 rows)
Results/Imports/2018/COMTRADE-FINAL-CA2042018H5[2025-12-10].gz: NaN 22691 -> 22691  (22030 rows)
Results/Imports/2018/COMTRADE-FINAL-CA2262018H5[2025-12-10].gz: NaN 18650 -> 18650  (18476 rows)
Results/Imports/2018/COMTRADE-FINAL-CA2312018H5[2025-12-10].gz: NaN 35507 -> 35507  (34480 rows)
Results/Imports/2018/COMTRADE-FINAL-CA2322018H5[2025-12-10].gz: NaN 7685 -> 7685  (7490 rows)
Results/Imports/2018/COMTRADE-FINAL-CA2622018H5[2025-12-10].gz: NaN 21576 -> 21576  (20944 rows)
Results/Imports/2018/COMTRADE-FINAL-CA2662018H5[2025-12-10].gz: NaN 29995 -> 29995  (28961 rows)
Results/Imports/2018/COMTRADE-FINAL-CA2702018H5[2025-12-10].gz: NaN 17284 -> 17284  (16980 rows)
Results/Imports/2018/COMTRADE-FINAL-CA2752018H5[2025-12-10].gz: NaN 9263 -> 9263  (9038 rows)
Results/Imports/2018/COMTRADE-FINAL-CA3242018H5[2025-12-10].gz: NaN 33391 -> 33391  (31749 rows)
Results/Imports/2018/COMTRADE-FINAL-CA3322018H5[2025-12-10].gz: NaN 22689 -> 22689  (21707 rows)
Results/Imports/2018/COMTRADE-FINAL-CA3682018H5[2025-12-10].gz: NaN 55106 -> 55106  (53627 rows)
Results/Imports/2018/COMTRADE-FINAL-CA4042018H5[2025-12-10].gz: NaN 59136 -> 59136  (57784 rows)
Results/Imports/2018/COMTRADE-FINAL-CA4082018H5[2025-12-10].gz: NaN 6207 -> 6207  (5566 rows)
Results/Imports/2018/COMTRADE-FINAL-CA4342018H5[2025-12-10].gz: NaN 34240 -> 34240  (33813 rows)
Results/Imports/2018/COMTRADE-FINAL-CA4542018H5[2025-12-10].gz: NaN 20370 -> 20370  (19775 rows)
Results/Imports/2018/COMTRADE-FINAL-CA4782018H5[2025-12-10].gz: NaN 24762 -> 24762  (24083 rows)
Results/Imports/2018/COMTRADE-FINAL-CA4842018H5[2025-12-10].gz: NaN 106070 -> 106070  (102213 rows)
Results/Imports/2018/COMTRADE-FINAL-CA4982018H5[2025-12-10].gz: NaN 50047 -> 50047  (47054 rows)
Results/Imports/2018/COMTRADE-FINAL-CA5242018H5[2025-12-10].gz: NaN 25401 -> 25401  (24410 rows)
Results/Imports/2018/COMTRADE-FINAL-CA5662018H5[2025-12-10].gz: NaN 67378 -> 67378  (65333 rows)
Results/Imports/2018/COMTRADE-FINAL-CA5982018H5[2025-12-10].gz: NaN 27838 -> 27838  (26407 rows)
Results/Imports/2018/COMTRADE-FINAL-CA6082018H5[2025-12-10].gz: NaN 85588 -> 85588  (82214 rows)
Results/Imports/2018/COMTRADE-FINAL-CA6262018H5[2025-12-10].gz: NaN 10166 -> 10166  (9859 rows)
Results/Imports/2018/COMTRADE-FINAL-CA6342018H5[2025-12-10].gz: NaN 80899 -> 80899  (78460 rows)
Results/Imports/2018/COMTRADE-FINAL-CA6822018H5[2025-12-10].gz: NaN 102940 -> 102940  (100141 rows)
Results/Imports/2018/COMTRADE-FINAL-CA6862018H5[2025-12-10].gz: NaN 45940 -> 45940  (44406 rows)
Results/Imports/2018/COMTRADE-FINAL-CA6942018H5[2025-12-10].gz: NaN 20054 -> 20054  (19440 rows)
Results/Imports/2018/COMTRADE-FINAL-CA7062018H5[2025-12-10].gz: NaN 16875 -> 16875  (16433 rows)
Results/Imports/2018/COMTRADE-FINAL-CA7282018H5[2025-12-10].gz: NaN 9481 -> 9481  (9298 rows)
Results/Imports/2018/COMTRADE-FINAL-CA7602018H5[2025-12-10].gz: NaN 26134 -> 26134  (24968 rows)
Results/Imports/2018/COMTRADE-FINAL-CA7622018H5[2025-12-10].gz: NaN 24685 -> 24685  (21719 rows)
Results/Imports/2018/COMTRADE-FINAL-CA7802018H5[2025-12-10].gz: NaN 32802 -> 32802  (31454 rows)
Results/Imports/2018/COMTRADE-FINAL-CA7952018H5[2025-12-10].gz: NaN 26998 -> 26998  (24581 rows)
Results/Imports/2018/COMTRADE-FINAL-CA8042018H5[2025-12-10].gz: NaN 101995 -> 101995  (96136 rows)
Results/Imports/2018/COMTRADE-FINAL-CA8182018H5[2025-12-10].gz: NaN 82312 -> 82312  (79539 rows)
Results/Imports/2018/COMTRADE-FINAL-CA8622018H5[2025-12-10].gz: NaN 31702 -> 31702  (30259 rows)
Results/Imports/2019/COMTRADE-FINAL-CA0042019H5[2025-12-10].gz: NaN 27290 -> 27290  (26735 rows)
Results/Imports/2019/COMTRADE-FINAL-CA0122019H5[2025-12-10].gz: NaN 53541 -> 53541  (52851 rows)
Results/Imports/2019/COMTRADE-FINAL-CA0502019H5[2025-12-10].gz: NaN 56439 -> 56439  (55043 rows)
Results/Imports/2019/COMTRADE-FINAL-CA1402019H5[2025-12-10].gz: NaN 12048 -> 12048  (11896 rows)
Results/Imports/2019/COMTRADE-FINAL-CA1482019H5[2025-12-10].gz: NaN 15146 -> 15146  (14850 rows)
Results/Imports/2019/COMTRADE-FINAL-CA1802019H5[2025-12-10].gz: NaN 44024 -> 44024  (43094 rows)
Results/Imports/2019/COMTRADE-FINAL-CA2262019H5[2025-12-10].gz: NaN 19372 -> 19372  (19125 rows)
Results/Imports/2019/COMTRADE-FINAL-CA2322019H5[2025-12-10].gz: NaN 7417 -> 7417  (7301 rows)
Results/Imports/2019/COMTRADE-FINAL-CA2622019H5[2025-12-10].gz: NaN 22283 -> 22283  (21871 rows)
Results/Imports/2019/COMTRADE-FINAL-CA2662019H5[2025-12-10].gz: NaN 31906 -> 31906  (31383 rows)
Results/Imports/2019/COMTRADE-FINAL-CA2702019H5[2025-12-10].gz: NaN 19716 -> 19716  (19567 rows)
Results/Imports/2019/COMTRADE-FINAL-CA2752019H5[2025-12-10].gz: NaN 9064 -> 9064  (9021 rows)
Results/Imports/2019/COMTRADE-FINAL-CA3242019H5[2025-12-10].gz: NaN 33504 -> 33504  (33021 rows)
Results/Imports/2019/COMTRADE-FINAL-CA3322019H5[2025-12-10].gz: NaN 20422 -> 20422  (19833 rows)
Results/Imports/2019/COMTRADE-FINAL-CA3682019H5[2025-12-10].gz: NaN 58401 -> 58401  (57580 rows)
Results/Imports/2019/COMTRADE-FINAL-CA4082019H5[2025-12-10].gz: NaN 4985 -> 4985  (4903 rows)
Results/Imports/2019/COMTRADE-FINAL-CA4262019H5[2025-12-10].gz: NaN 9181 -> 9181  (8884 rows)
Results/Imports/2019/COMTRADE-FINAL-CA4782019H5[2025-12-10].gz: NaN 26943 -> 26943  (26615 rows)
Results/Imports/2019/COMTRADE-FINAL-CA4842019H5[2025-12-10].gz: NaN 107802 -> 107802  (105084 rows)
Results/Imports/2019/COMTRADE-FINAL-CA4982019H5[2025-12-10].gz: NaN 49114 -> 49114  (48803 rows)
Results/Imports/2019/COMTRADE-FINAL-CA5662019H5[2025-12-10].gz: NaN 71237 -> 71237  (69624 rows)
Results/Imports/2019/COMTRADE-FINAL-CA6242019H5[2025-12-10].gz: NaN 8843 -> 8843  (8867 rows)
Results/Imports/2019/COMTRADE-FINAL-CA6262019H5[2025-12-10].gz: NaN 10537 -> 10537  (10244 rows)
Results/Imports/2019/COMTRADE-FINAL-CA6342019H5[2025-12-10].gz: NaN 81885 -> 81885  (80235 rows)
Results/Imports/2019/COMTRADE-FINAL-CA6462019H5[2025-12-10].gz: NaN 25645 -> 25645  (25237 rows)
Results/Imports/2019/COMTRADE-FINAL-CA6822019H5[2025-12-10].gz: NaN 105311 -> 105311  (103245 rows)
Results/Imports/2019/COMTRADE-FINAL-CA6942019H5[2025-12-10].gz: NaN 20669 -> 20669  (20316 rows)
Results/Imports/2019/COMTRADE-FINAL-CA7062019H5[2025-12-10].gz: NaN 19896 -> 19896  (19581 rows)
Results/Imports/2019/COMTRADE-FINAL-CA7282019H5[2025-12-10].gz: NaN 12954 -> 12954  (12735 rows)
Results/Imports/2019/COMTRADE-FINAL-CA7292019H5[2025-12-10].gz: NaN 32279 -> 32279  (31836 rows)
Results/Imports/2019/COMTRADE-FINAL-CA7602019H5[2025-12-10].gz: NaN 23871 -> 23871  (23683 rows)
Results/Imports/2019/COMTRADE-FINAL-CA7622019H5[2025-12-10].gz: NaN 21905 -> 21905  (21699 rows)
Results/Imports/2019/COMTRADE-FINAL-CA7802019H5[2025-12-10].gz: NaN 35333 -> 35333  (34089 rows)
Results/Imports/2019/COMTRADE-FINAL-CA7952019H5[2025-12-10].gz: NaN 24814 -> 24814  (24592 rows)
Results/Imports/2019/COMTRADE-FINAL-CA8042019H5[2025-12-10].gz: NaN 100242 -> 100242  (99053 rows)
Results/Imports/2019/COMTRADE-FINAL-CA8182019H5[2025-12-10].gz: NaN 82417 -> 82417  (81007 rows)
Results/Imports/2019/COMTRADE-FINAL-CA8622019H5[2025-12-10].gz: NaN 32798 -> 32798  (31889 rows)
Results/Imports/2020/COMTRADE-FINAL-CA0042020H5[2025-12-10].gz: NaN 27017 -> 27017  (26440 rows)
Results/Imports/2020/COMTRADE-FINAL-CA0122020H5[2025-12-10].gz: NaN 50442 -> 50442  (49966 rows)
Results/Imports/2020/COMTRADE-FINAL-CA0502020H5[2025-12-10].gz: NaN 54024 -> 54024  (52605 rows)
Results/Imports/2020/COMTRADE-FINAL-CA1402020H5[2025-12-10].gz: NaN 11930 -> 11930  (11943 rows)
Results/Imports/2020/COMTRADE-FINAL-CA1482020H5[2025-12-10].gz: NaN 14836 -> 14836  (14563 rows)
Results/Imports/2020/COMTRADE-FINAL-CA1802020H5[2025-12-10].gz: NaN 43429 -> 43429  (42360 rows)
Results/Imports/2020/COMTRADE-FINAL-CA2262020H5[2025-12-10].gz: NaN 18364 -> 18364  (18154 rows)
Results/Imports/2020/COMTRADE-FINAL-CA2322020H5[2025-12-10].gz: NaN 6588 -> 6588  (6499 rows)
Results/Imports/2020/COMTRADE-FINAL-CA2622020H5[2025-12-10].gz: NaN 23468 -> 23468  (22989 rows)
Results/Imports/2020/COMTRADE-FINAL-CA2702020H5[2025-12-10].gz: NaN 18878 -> 18878  (18644 rows)
Results/Imports/2020/COMTRADE-FINAL-CA2752020H5[2025-12-10].gz: NaN 9094 -> 9094  (9100 rows)
Results/Imports/2020/COMTRADE-FINAL-CA2882020H5[2025-12-10].gz: NaN 58122 -> 58122  (56821 rows)
Results/Imports/2020/COMTRADE-FINAL-CA3242020H5[2025-12-10].gz: NaN 33375 -> 33375  (32845 rows)
Results/Imports/2020/COMTRADE-FINAL-CA3322020H5[2025-12-10].gz: NaN 21290 -> 21290  (20492 rows)
Results/Imports/2020/COMTRADE-FINAL-CA3682020H5[2025-12-10].gz: NaN 55601 -> 55601  (54976 rows)
Results/Imports/2020/COMTRADE-FINAL-CA4082020H5[2025-12-10].gz: NaN 3666 -> 3666  (3627 rows)
Results/Imports/2020/COMTRADE-FINAL-CA4342020H5[2025-12-10].gz: NaN 37270 -> 37270  (37086 rows)
Results/Imports/2020/COMTRADE-FINAL-CA4842020H5[2025-12-10].gz: NaN 104033 -> 104033  (101459 rows)
Results/Imports/2020/COMTRADE-FINAL-CA5662020H5[2025-12-10].gz: NaN 65876 -> 65876  (64423 rows)
Results/Imports/2020/COMTRADE-FINAL-CA6242020H5[2025-12-10].gz: NaN 8854 -> 8854  (8796 rows)
Results/Imports/2020/COMTRADE-FINAL-CA6462020H5[2025-12-10].gz: NaN 24634 -> 24634  (24223 rows)
Results/Imports/2020/COMTRADE-FINAL-CA6822020H5[2025-12-10].gz: NaN 103516 -> 103516  (101497 rows)
Results/Imports/2020/COMTRADE-FINAL-CA6942020H5[2025-12-10].gz: NaN 20625 -> 20625  (20210 rows)
Results/Imports/2020/COMTRADE-FINAL-CA7062020H5[2025-12-10].gz: NaN 19278 -> 19278  (19029 rows)
Results/Imports/2020/COMTRADE-FINAL-CA7282020H5[2025-12-10].gz: NaN 12532 -> 12532  (12366 rows)
Results/Imports/2020/COMTRADE-FINAL-CA7292020H5[2025-12-10].gz: NaN 32397 -> 32397  (31984 rows)
Results/Imports/2020/COMTRADE-FINAL-CA7602020H5[2025-12-10].gz: NaN 18846 -> 18846  (18738 rows)
Results/Imports/2020/COMTRADE-FINAL-CA7622020H5[2025-12-10].gz: NaN 20965 -> 20965  (21024 rows)
Results/Imports/2020/COMTRADE-FINAL-CA7802020H5[2025-12-10].gz: NaN 33072 -> 33072  (31735 rows)
Results/Imports/2020/COMTRADE-FINAL-CA7952020H5[2025-12-10].gz: NaN 23646 -> 23646  (23472 rows)
Results/Imports/2020/COMTRADE-FINAL-CA8182020H5[2025-12-10].gz: NaN 81034 -> 81034  (79842 rows)
Results/Imports/2020/COMTRADE-FINAL-CA8622020H5[2025-12-10].gz: NaN 32321 -> 32321  (31260 rows)
Results/Imports/2020/COMTRADE-FINAL-CA8872020H5[2025-12-10].gz: NaN 24793 -> 24793  (24514 rows)
Results/Imports/2021/COMTRADE-FINAL-CA0042021H5[2025-12-10].gz: NaN 22163 -> 22163  (21816 rows)
Results/Imports/2021/COMTRADE-FINAL-CA0122021H5[2025-12-10].gz: NaN 50150 -> 50150  (49821 rows)
Results/Imports/2021/COMTRADE-FINAL-CA0502021H5[2025-12-10].gz: NaN 56049 -> 56049  (55005 rows)
Results/Imports/2021/COMTRADE-FINAL-CA1402021H5[2025-12-10].gz: NaN 12566 -> 12566  (12481 rows)
Results/Imports/2021/COMTRADE-FINAL-CA1482021H5[2025-12-10].gz: NaN 13800 -> 13800  (13658 rows)
Results/Imports/2021/COMTRADE-FINAL-CA2262021H5[2025-12-10].gz: NaN 17889 -> 17889  (17809 rows)
Results/Imports/2021/COMTRADE-FINAL-CA2322021H5[2025-12-10].gz: NaN 7638 -> 7638  (7551 rows)
Results/Imports/2021/COMTRADE-FINAL-CA2622021H5[2025-12-10].gz: NaN 24176 -> 24176  (23865 rows)
Results/Imports/2021/COMTRADE-FINAL-CA2752021H5[2025-12-10].gz: NaN 10848 -> 10848  (10815 rows)
Results/Imports/2021/COMTRADE-FINAL-CA3242021H5[2025-12-10].gz: NaN 35448 -> 35448  (35007 rows)
Results/Imports/2021/COMTRADE-FINAL-CA3322021H5[2025-12-10].gz: NaN 19754 -> 19754  (19414 rows)
Results/Imports/2021/COMTRADE-FINAL-CA3682021H5[2025-12-10].gz: NaN 57055 -> 57055  (56584 rows)
Results/Imports/2021/COMTRADE-FINAL-CA4082021H5[2025-12-10].gz: NaN 1455 -> 1455  (1419 rows)
Results/Imports/2021/COMTRADE-FINAL-CA4342021H5[2025-12-10].gz: NaN 40789 -> 40789  (40639 rows)
Results/Imports/2021/COMTRADE-FINAL-CA5662021H5[2025-12-10].gz: NaN 68100 -> 68100  (67100 rows)
Results/Imports/2021/COMTRADE-FINAL-CA6242021H5[2025-12-10].gz: NaN 9899 -> 9899  (9912 rows)
Results/Imports/2021/COMTRADE-FINAL-CA6462021H5[2025-12-10].gz: NaN 26771 -> 26771  (26362 rows)
Results/Imports/2021/COMTRADE-FINAL-CA6942021H5[2025-12-10].gz: NaN 23673 -> 23673  (23375 rows)
Results/Imports/2021/COMTRADE-FINAL-CA7062021H5[2025-12-10].gz: NaN 20796 -> 20796  (20537 rows)
Results/Imports/2021/COMTRADE-FINAL-CA7282021H5[2025-12-10].gz: NaN 13989 -> 13989  (13731 rows)
Results/Imports/2021/COMTRADE-FINAL-CA7292021H5[2025-12-10].gz: NaN 31490 -> 31490  (31176 rows)
Results/Imports/2021/COMTRADE-FINAL-CA7602021H5[2025-12-10].gz: NaN 17251 -> 17251  (17113 rows)
Results/Imports/2021/COMTRADE-FINAL-CA7622021H5[2025-12-10].gz: NaN 23844 -> 23844  (23655 rows)
Results/Imports/2021/COMTRADE-FINAL-CA7802021H5[2025-12-10].gz: NaN 30781 -> 30781  (30173 rows)
Results/Imports/2021/COMTRADE-FINAL-CA7952021H5[2025-12-10].gz: NaN 24562 -> 24562  (24421 rows)
Results/Imports/2021/COMTRADE-FINAL-CA8182021H5[2025-12-10].gz: NaN 84187 -> 84187  (83307 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Imports/2025/COMTRADE-FINAL-AFG2025H5[2025-12-10].gz: NaN 471324 -> 218829  (16833 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Imports/2025/COMTRADE-FINAL-ALB2025H5[2025-12-10].gz: NaN 821688 -> 381498  (29346 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Imports/2025/COMTRADE-FINAL-ARE2025H5[2025-12-10].gz: NaN 3969000 -> 1842750  (141750 rows)
Results/Imports/2025/COMTRADE-FINAL-BDI2025H5[2025-12-10].gz: NaN 70168 -> 32578  (2506 rows)
Results/Imports/2025/COMTRADE-FINAL-BEN2025H5[2025-12-10].gz: NaN 143528 -> 66638  (5126 rows)
Results/Imports/2025/COMTRADE-FINAL-BFA2025H5[2025-12-10].gz: NaN 157332 -> 73047  (5619 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Imports/2025/COMTRADE-FINAL-BGD2025H5[2025-12-10].gz: NaN 1713068 -> 795353  (61181 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Imports/2025/COMTRADE-FINAL-BHR2025H5[2025-12-10].gz: NaN 556780 -> 258505  (19885 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Imports/2025/COMTRADE-FINAL-BLR2025H5[2025-12-10].gz: NaN 639352 -> 296842  (22834 rows)
Results/Imports/2025/COMTRADE-FINAL-BWA2025H5[2025-12-10].gz: NaN 149996 -> 69641  (5357 rows)
Results/Imports/2025/COMTRADE-FINAL-CAF2025H5[2025-12-10].gz: NaN 71988 -> 33423  (2571 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Imports/2025/COMTRADE-FINAL-CMR2025H5[2025-12-10].gz: NaN 369208 -> 171418  (13186 rows)
Results/Imports/2025/COMTRADE-FINAL-COD2025H5[2025-12-10].gz: NaN 216524 -> 100529  (7733 rows)
Results/Imports/2025/COMTRADE-FINAL-COG2025H5[2025-12-10].gz: NaN 151816 -> 70486  (5422 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Imports/2025/COMTRADE-FINAL-CRI2025H5[2025-12-10].gz: NaN 883456 -> 410176  (31552 rows)
Results/Imports/2025/COMTRADE-FINAL-CUB2025H5[2025-12-10].gz: NaN 101444 -> 47099  (3623 rows)
Results/Imports/2025/COMTRADE-FINAL-DJI2025H5[2025-12-10].gz: NaN 52976 -> 24596  (1892 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Imports/2025/COMTRADE-FINAL-DZA2025H5[2025-12-10].gz: NaN 338044 -> 156949  (12073 rows)
Results/Imports/2025/COMTRADE-FINAL-ERI2025H5[2025-12-10].gz: NaN 51660 -> 23985  (1845 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Imports/2025/COMTRADE-FINAL-ETH2025H5[2025-12-10].gz: NaN 422296 -> 196066  (15082 rows)
Results/Imports/2025/COMTRADE-FINAL-GAB2025H5[2025-12-10].gz: NaN 126140 -> 58565  (4505 rows)
Results/Imports/2025/COMTRADE-FINAL-GIN2025H5[2025-12-10].gz: NaN 148288 -> 68848  (5296 rows)
Results/Imports/2025/COMTRADE-FINAL-GMB2025H5[2025-12-10].gz: NaN 64232 -> 29822  (2294 rows)
Results/Imports/2025/COMTRADE-FINAL-GNB2025H5[2025-12-10].gz: NaN 13720 -> 6370  (490 rows)
Results/Imports/2025/COMTRADE-FINAL-GNQ2025H5[2025-12-10].gz: NaN 67760 -> 31460  (2420 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Imports/2025/COMTRADE-FINAL-HND2025H5[2025-12-10].gz: NaN 506884 -> 235339  (18103 rows)
Results/Imports/2025/COMTRADE-FINAL-HTI2025H5[2025-12-10].gz: NaN 169652 -> 78767  (6059 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Imports/2025/COMTRADE-FINAL-IRN2025H5[2025-12-10].gz: NaN 978628 -> 454363  (34951 rows)
Results/Imports/2025/COMTRADE-FINAL-IRQ2025H5[2025-12-10].gz: NaN 237384 -> 110214  (8478 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Imports/2025/COMTRADE-FINAL-JOR2025H5[2025-12-10].gz: NaN 850024 -> 394654  (30358 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Imports/2025/COMTRADE-FINAL-KHM2025H5[2025-12-10].gz: NaN 1258656 -> 584376  (44952 rows)
Results/Imports/2025/COMTRADE-FINAL-LAO2025H5[2025-12-10].gz: NaN 379988 -> 176423  (13571 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Imports/2025/COMTRADE-FINAL-LBN2025H5[2025-12-10].gz: NaN 873768 -> 405678  (31206 rows)
Results/Imports/2025/COMTRADE-FINAL-LBR2025H5[2025-12-10].gz: NaN 81004 -> 37609  (2893 rows)
Results/Imports/2025/COMTRADE-FINAL-LBY2025H5[2025-12-10].gz: NaN 100156 -> 46501  (3577 rows)
Results/Imports/2025/COMTRADE-FINAL-LSO2025H5[2025-12-10].gz: NaN 96488 -> 44798  (3446 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Imports/2025/COMTRADE-FINAL-MDG2025H5[2025-12-10].gz: NaN 542108 -> 251693  (19361 rows)
Results/Imports/2025/COMTRADE-FINAL-MLI2025H5[2025-12-10].gz: NaN 161448 -> 74958  (5766 rows)
Results/Imports/2025/COMTRADE-FINAL-MNG2025H5[2025-12-10].gz: NaN 220528 -> 102388  (7876 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Imports/2025/COMTRADE-FINAL-MRT2025H5[2025-12-10].gz: NaN 107604 -> 49959  (3843 rows)
Results/Imports/2025/COMTRADE-FINAL-NAM2025H5[2025-12-10].gz: NaN 403200 -> 187200  (14400 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Imports/2025/COMTRADE-FINAL-NER2025H5[2025-12-10].gz: NaN 148204 -> 68809  (5293 rows)
Results/Imports/2025/COMTRADE-FINAL-NIC2025H5[2025-12-10].gz: NaN 359716 -> 167011  (12847 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Imports/2025/COMTRADE-FINAL-NPL2025H5[2025-12-10].gz: NaN 594580 -> 276055  (21235 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Imports/2025/COMTRADE-FINAL-PER2025H5[2025-12-10].gz: NaN 1449644 -> 673049  (51773 rows)
Results/Imports/2025/COMTRADE-FINAL-PNG2025H5[2025-12-10].gz: NaN 114464 -> 53144  (4088 rows)
Results/Imports/2025/COMTRADE-FINAL-PRK2025H5[2025-12-10].gz: NaN 116676 -> 54171  (4167 rows)
Results/Imports/2025/COMTRADE-FINAL-PSE2025H5[2025-12-10].gz: NaN 73500 -> 34125  (2625 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Imports/2025/COMTRADE-FINAL-QAT2025H5[2025-12-10].gz: NaN 717864 -> 333294  (25638 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Imports/2025/COMTRADE-FINAL-RUS2025H5[2025-12-10].gz: NaN 1973888 -> 916448  (70496 rows)
Results/Imports/2025/COMTRADE-FINAL-RWA2025H5[2025-12-10].gz: NaN 170520 -> 79170  (6090 rows)
Results/Imports/2025/COMTRADE-FINAL-SDN2025H5[2025-12-10].gz: NaN 73416 -> 34086  (2622 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Imports/2025/COMTRADE-FINAL-SEN2025H5[2025-12-10].gz: NaN 344176 -> 159796  (12292 rows)
Results/Imports/2025/COMTRADE-FINAL-SLE2025H5[2025-12-10].gz: NaN 278376 -> 129246  (9942 rows)
Results/Imports/2025/COMTRADE-FINAL-SOM2025H5[2025-12-10].gz: NaN 78708 -> 36543  (2811 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Imports/2025/COMTRADE-FINAL-SWZ2025H5[2025-12-10].gz: NaN 321272 -> 149162  (11474 rows)
Results/Imports/2025/COMTRADE-FINAL-SYR2025H5[2025-12-10].gz: NaN 271768 -> 126178  (9706 rows)
Results/Imports/2025/COMTRADE-FINAL-TCD2025H5[2025-12-10].gz: NaN 93604 -> 43459  (3343 rows)
Results/Imports/2025/COMTRADE-FINAL-TJK2025H5[2025-12-10].gz: NaN 82684 -> 38389  (2953 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Imports/2025/COMTRADE-FINAL-TKM2025H5[2025-12-10].gz: NaN 91700 -> 42575  (3275 rows)
Results/Imports/2025/COMTRADE-FINAL-TLS2025H5[2025-12-10].gz: NaN 67788 -> 31473  (2421 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Imports/2025/COMTRADE-FINAL-TUN2025H5[2025-12-10].gz: NaN 1549044 -> 719199  (55323 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Imports/2025/COMTRADE-FINAL-UKR2025H5[2025-12-10].gz: NaN 2542792 -> 1180582  (90814 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Imports/2025/COMTRADE-FINAL-UZB2025H5[2025-12-10].gz: NaN 567700 -> 263575  (20275 rows)
Results/Imports/2025/COMTRADE-FINAL-VEN2025H5[2025-12-10].gz: NaN 261604 -> 121459  (9343 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Imports/2025/COMTRADE-FINAL-VNM2025H5[2025-12-10].gz: NaN 4542832 -> 2109172  (162244 rows)
Results/Imports/2025/COMTRADE-FINAL-YEM2025H5[2025-12-10].gz: NaN 95760 -> 44460  (3420 rows)
Results/Imports/2025/COMTRADE-FINAL-ZMB2025H5[2025-12-10].gz: NaN 255920 -> 118820  (9140 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)
/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Imports/2025/COMTRADE-FINAL-ZWE2025H5[2025-12-10].gz: NaN 239344 -> 111124  (8548 rows)

/var/folders/13/n6g9f1g56kz51t0nxp0_xbcr0000gq/T/ipykernel_2949/1228799318.py:35: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(val)

Results/Imports/COMTRADE-FINAL-ALL-imports-imputed-2025[2025-12-10].csv.gz: NaN 36216852 -> 16814967  (1293459 rows)

EOFError: Compressed file ended before the end-of-stream marker was reached